In [54]:
import pandas as pd

In [55]:
train = pd.read_csv('train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
train2 = train.drop(['Name', 'Cabin'], axis=1)
train2.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,female,35.0,1,0,113803,53.1000,S
4,5,0,3,male,35.0,0,0,373450,8.0500,S

In [57]:
train.groupby(['Pclass', 'Sex', 'Survived']).count()

                        PassengerId  Name  Age  SibSp  Parch  Ticket  Fare  \
Pclass Sex    Survived
1      female 0                   3     3    3      3      3       3     3
              1                  91    91   82     91     91      91    91
       male   0                  77    77   61     77     77      77    77
              1                  45    45   40     45     45      45    45
2      female 0                   6     6    6      6      6       6     6
              1                  70    70   68     70     70      70    70
       male   0                  91    91   84     91     91      91    91
              1                  17    17   15     17     17      17    17
3      female 0                  72    72   55     72     72      72    72
              1                  72    72   47     72     72      72    72
       male   0                 300   300  215    300    300     300   300
              1                  47    47   38     47     47      47    47

                        Cabin  Embarked
Pclass Sex    Survived
1      female 0             3         3
              1            78        89
       male   0            56        77
              1            39        45
2      female 0             1         6
              1             9        70
       male   0             2        91
              1             4        17
3      female 0             2        72
              1             4        72
       male   0             4       300
              1             2        47

In [58]:
train.groupby(['Pclass', 'Sex', 'Survived'], as_index=False).count()

,Pclass,Sex,Survived,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,female,0,3,3,3,3,3,3,3,3,3
1,1,female,1,91,91,82,91,91,91,91,78,89
2,1,male,0,77,77,61,77,77,77,77,56,77
3,1,male,1,45,45,40,45,45,45,45,39,45
4,2,female,0,6,6,6,6,6,6,6,1,6
5,2,female,1,70,70,68,70,70,70,70,9,70
6,2,male,0,91,91,84,91,91,91,91,2,91
7,2,male,1,17,17,15,17,17,17,17,4,17
8,3,female,0,72,72,55,72,72,72,72,2,72
9,3,female,1,72,72,47,72,72,72,72,4,72
10,3,male,0,300,300,215,300,300,300,300,4,300
11,3,male,1,47,47,38,47,47,47,47,2,47

### 데이터 셋 보여주는 최대 행, 열 값

In [59]:
pd.options.display.max_rows

60

In [60]:
pd.options.display.max_columns

20

In [61]:
pd.options.display.max_rows = 1000
pd.options.display.max_columns = 500

In [62]:
pd.options.display.max_rows

1000

In [63]:
train2

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,male,22.00,1,0,A/5 21171,7.2500,S
1,2,1,1,female,38.00,1,0,PC 17599,71.2833,C
2,3,1,3,female,26.00,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,female,35.00,1,0,113803,53.1000,S
4,5,0,3,male,35.00,0,0,373450,8.0500,S
5,6,0,3,male,NaN,0,0,330877,8.4583,Q
6,7,0,1,male,54.00,0,0,17463,51.8625,S
7,8,0,3,male,2.00,3,1,349909,21.0750,S
8,9,1,3,female,27.00,0,2,347742,11.1333,S
9,10,1,2,female,14.00,1,0,237736,30.0708,C
10,11,1,3,female,4.00,1,1,PP 9549,16.7000,S
11,12,1,1,female,58.00,0,0,113783,26.5500,S
12,13,0,3,male,20.00,0,0,A/5. 2151,8.0500,S
13,14,0,3,male,39.00,1,5,347082,31.2750,S
14,15,0,3,female,14.00,0,0,350406,7.8542,S
15,16,1,2,female,55.00,0,0,248706,16.0000,S
16,17,0,3,male,2.00,4,1,382652,29.1250,Q
17,18,1,2,male,NaN,0,0,244373,13.0000,S
18,19,0,3,female,31.00,1,0,345763,18.0000,S
19,20,1,3,female,NaN,0,0,2649,7.2250,C
20,21,0,2,male,35.00,0,0,239865,26.0000,S
21,22,1,2,male,34.00,0,0,248698,13.0000,S
22,23,1,3,female,15.00,0,0,330923,8.0292,Q
23,24,1,1,male,28.00,0,0,113788,35.5000,S
24,25,0,3,female,8.00,3,1,349909,21.0750,S
25,26,1,3,female,38.00,1,5,347077,31.3875,S
26,27,0,3,male,NaN,0,0,2631,7.2250,C
27,28,0,1,male,19.00,3,2,19950,263.0000,S
28,29,1,3,female,NaN,0,0,330959,7.8792,Q
29,30,0,3,male,NaN,0,0,349216,7.8958,S
30,31,0,1,male,40.00,0,0,PC 17601,27.7208,C
31,32,1,1,female,NaN,1,0,PC 17569,146.5208,C
32,33,1,3,female,NaN,0,0,335677,7.7500,Q
33,34,0,2,male,66.00,0,0,C.A. 24579,10.5000,S
34,35,0,1,male,28.00,1,0,PC 17604,82.1708,C
35,36,0,1,male,42.00,1,0,113789,52.0000,S
36,37,1,3,male,NaN,0,0,2677,7.2292,C
37,38,0,3,male,21.00,0,0,A./5. 2152,8.0500,S
38,39,0,3,female,18.00,2,0,345764,18.0000,S
39,40,1,3,female,14.00,1,0,2651,11.2417,C
40,41,0,3,female,40.00,1,0,7546,9.4750,S
41,42,0,2,female,27.00,1,0,11668,21.0000,S
42,43,0,3,male,NaN,0,0,349253,7.8958,C
43,44,1,2,female,3.00,1,2,SC/Paris 2123,41.5792,C
44,45,1,3,female,19.00,0,0,330958,7.8792,Q
45,46,0,3,male,NaN,0,0,S.C./A.4. 23567,8.0500,S
46,47,0,3,male,NaN,1,0,370371,15.5000,Q
47,48,1,3,female,NaN,0,0,14311,7.7500,Q
48,49,0,3,male,NaN,2,0,2662,21.6792,C
49,50,0,3,female,18.00,1,0,349237,17.8000,S
50,51,0,3,male,7.00,4,1,3101295,39.6875,S
51,52,0,3,male,21.00,0,0,A/4. 39886,7.8000,S
52,53,1,1,female,49.00,1,0,PC 17572,76.7292,C
53,54,1,2,female,29.00,1,0,2926,26.0000,S
54,55,0,1,male,65.00,0,1,113509,61.9792,C
55,56,1,1,male,NaN,0,0,19947,35.5000,S
56,57,1,2,female,21.00,0,0,C.A. 31026,10.5000,S
57,58,0,3,male,28.50,0,0,2697,7.2292,C
58,59,1,2,female,5.00,1,2,C.A. 34651,27.7500,S
59,60,0,3,male,11.00,5,2,CA 2144,46.9000,S
60,61,0,3,male,22.00,0,0,2669,7.2292,C
61,62,1,1,female,38.00,0,0,113572,80.0000,NaN
62,63,0,1,male,45.00,1,0,36973,83.4750,S
63,64,0,3,male,4.00,3,2,347088,27.9000,S
64,65,0,1,male,NaN,0,0,PC 17605,27.7208,C
65,66,1,3,male,NaN,1,1,2661,15.2458,C
66,67,1,2,female,29.00,0,0,C.A. 29395,10.5000,S
67,68,0,3,male,19.00,0,0,S.P. 3464,8.1583,S
68,69,1,3,female,17.00,4,2,3101281,7.9250,S
69,70,0,3,male,26.00,2,0,315151,8.6625,S
70,71,0,2,male,32.00,0,0,C.A. 33111,10.5000,S
71,72,0,3,female,16.00,5,2,CA 2144,46.9000,S
72,73,0,2,male,21.00,0,0,S.O.C. 14879,73.5000,S
73,74,0,3,male,26.00,1,0,2680,14.4542,C
74,75,1,3,male,32.00,0,0,1601,56.4958,S
75,76,0,3,male,25.00,0,0,348123,7.6500,S
76,77,0,3,male,NaN,0,0,349208,7.8958,S
77,78,0,3,male,NaN,0,0,374746,8.0500,S
78,79,1,2,male,0.83,0,2,248738,29.0000,S
79,80,1,3,female,30.00,0,0,364516,12.4750,S
80,81,0,3,male,22.00,0,0,345767,9.0000,S
81,82,1,3,male,29.00,0,0,345779,9.5000,S
82,83,1,3,female,NaN,0,0,330932,7.7875,Q
83,84,0,1,male,28.00,0,0,113059,47.1000,S
84,85,1,2,female,17.00,0,0,SO/C 14885,10.5000,S
85,86,1,3,female,33.00,3,0,3101278,15.8500,S
86,87,0,3,male,16.00,1,3,W./C. 6608,34.3750,S
87,88,0,3,male,NaN,0,0,SOTON/OQ 392086,8.0500,S
88,89,1,1,female,23.00,3,2,19950,263.0000,S
89,90,0,3,male,24.00,0,0,343275,8.0500,S
90,91,0,3,male,29.00,0,0,343276,8.0500,S
91,92,0,3,male,20.00,0,0,347466,7.8542,S
92,93,0,1,male,46.00,1,0,W.E.P. 5734,61.1750,S
93,94,0,3,male,26.00,1,2,C.A. 2315,20.5750,S
94,95,0,3,male,59.00,0,0,364500,7.2500,S
95,96,0,3,male,NaN,0,0,374910,8.0500,S
96,97,0,1,male,71.00,0,0,PC 17754,34.6542,C
97,98,1,1,male,23.00,0,1,PC 17759,63.3583,C
98,99,1,2,female,34.00,0,1,231919,23.0000,S
99,100,0,2,male,34.00,1,0,244367,26.0000,S
100,101,0,3,female,28.00,0,0,349245,7.8958,S
101,102,0,3,male,NaN,0,0,349215,7.8958,S
102,103,0,1,male,21.00,0,1,35281,77.2875,S
103,104,0,3,male,33.00,0,0,7540,8.6542,S
104,105,0,3,male,37.00,2,0,3101276,7.9250,S
105,106,0,3,male,28.00,0,0,349207,7.8958,S
106,107,1,3,female,21.00,0,0,343120,7.6500,S
107,108,1,3,male,NaN,0,0,312991,7.7750,S
108,109,0,3,male,38.00,0,0,349249,7.8958,S
109,110,1,3,female,NaN,1,0,371110,24.1500,Q
110,111,0,1,male,47.00,0,0,110465,52.0000,S
111,112,0,3,female,14.50,1,0,2665,14.4542,C
112,113,0,3,male,22.00,0,0,324669,8.0500,S
113,114,0,3,female,20.00,1,0,4136,9.8250,S
114,115,0,3,female,17.00,0,0,2627,14.4583,C
115,116,0,3,male,21.00,0,0,STON/O 2. 3101294,7.9250,S
116,117,0,3,male,70.50,0,0,370369,7.7500,Q
117,118,0,2,male,29.00,1,0,11668,21.0000,S
118,119,0,1,male,24.00,0,1,PC 17558,247.5208,C
119,120,0,3,female,2.00,4,2,347082,31.2750,S
120,121,0,2,male,21.00,2,0,S.O.C. 14879,73.5000,S
121,122,0,3,male,NaN,0,0,A4. 54510,8.0500,S
122,123,0,2,male,32.50,1,0,237736,30.0708,C
123,124,1,2,female,32.50,0,0,27267,13.0000,S
124,125,0,1,male,54.00,0,1,35281,77.2875,S
125,126,1,3,male,12.00,1,0,2651,11.2417,C
126,127,0,3,male,NaN,0,0,370372,7.7500,Q
127,128,1,3,male,24.00,0,0,C 17369,7.1417,S
128,129,1,3,female,NaN,1,1,2668,22.3583,C
129,130,0,3,male,45.00,0,0,347061,6.9750,S
130,131,0,3,male,33.00,0,0,349241,7.8958,C
131,132,0,3,male,20.00,0,0,SOTON/O.Q. 3101307,7.0500,S
132,133,0,3,female,47.00,1,0,A/5. 3337,14.5000,S
133,134,1,2,female,29.00,1,0,228414,26.0000,S
134,135,0,2,male,25.00,0,0,C.A. 29178,13.0000,S
135,136,0,2,male,23.00,0,0,SC/PARIS 2133,15.0458,C
136,137,1,1,female,19.00,0,2,11752,26.2833,S
137,138,0,1,male,37.00,1,0,113803,53.1000,S
138,139,0,3,male,16.00,0,0,7534,9.2167,S
139,140,0,1,male,24.00,0,0,PC 17593,79.2000,C
140,141,0,3,female,NaN,0,2,2678,15.2458,C
141,142,1,3,female,22.00,0,0,347081,7.7500,S
142,143,1,3,female,24.00,1,0,STON/O2. 3101279,15.8500,S
143,144,0,3,male,19.00,0,0,365222,6.7500,Q
144,145,0,2,male,18.00,0,0,231945,11.5000,S
145,146,0,2,male,19.00,1,1,C.A. 33112,36.7500,S
146,147,1,3,male,27.00,0,0,350043,7.7958,S
147,148,0,3,female,9.00,2,2,W./C. 6608,34.3750,S
148,149,0,2,male,36.50,0,2,230080,26.0000,S
149,150,0,2,male,42.00,0,0,244310,13.0000,S
150,151,0,2,male,51.00,0,0,S.O.P. 1166,12.5250,S
151,152,1,1,female,22.00,1,0,113776,66.6000,S
152,153,0,3,male,55.50,0,0,A.5. 11206,8.0500,S
153,154,0,3,male,40.50,0,2,A/5. 851,14.5000,S
154,155,0,3,male,NaN,0,0,Fa 265302,7.3125,S
155,156,0,1,male,51.00,0,1,PC 17597,61.3792,C
156,157,1,3,female,16.00,0,0,35851,7.7333,Q
157,158,0,3,male,30.00,0,0,SOTON/OQ 392090,8.0500,S
158,159,0,3,male,NaN,0,0,315037,8.6625,S
159,160,0,3,male,NaN,8,2,CA. 2343,69.5500,S
160,161,0,3,male,44.00,0,1,371362,16.1000,S
161,162,1,2,female,40.00,0,0,C.A. 33595,15.7500,S
162,163,0,3,male,26.00,0,0,347068,7.7750,S
163,164,0,3,male,17.00,0,0,315093,8.6625,S
164,165,0,3,male,1.00,4,1,3101295,39.6875,S
165,166,1,3,male,9.00,0,2,363291,20.5250,S
166,167,1,1,female,NaN,0,1,113505,55.0000,S
167,168,0,3,female,45.00,1,4,347088,27.9000,S
168,169,0,1,male,NaN,0,0,PC 17318,25.9250,S
169,170,0,3,male,28.00,0,0,1601,56.4958,S
170,171,0,1,male,61.00,0,0,111240,33.5000,S
171,172,0,3,male,4.00,4,1,382652,29.1250,Q
172,173,1,3,female,1.00,1,1,347742,11.1333,S
173,174,0,3,male,21.00,0,0,STON/O 2. 3101280,7.9250,S
174,175,0,1,male,56.00,0,0,17764,30.6958,C
175,176,0,3,male,18.00,1,1,350404,7.8542,S
176,177,0,3,male,NaN,3,1,4133,25.4667,S
177,178,0,1,female,50.00,0,0,PC 17595,28.7125,C
178,179,0,2,male,30.00,0,0,250653,13.0000,S
179,180,0,3,male,36.00,0,0,LINE,0.0000,S
180,181,0,3,female,NaN,8,2,CA. 2343,69.5500,S
181,182,0,2,male,NaN,0,0,SC/PARIS 2131,15.0500,C
182,183,0,3,male,9.00,4,2,347077,31.3875,S
183,184,1,2,male,1.00,2,1,230136,39.0000,S
184,185,1,3,female,4.00,0,2,315153,22.0250,S
185,186,0,1,male,NaN,0,0,113767,50.0000,S
186,187,1,3,female,NaN,1,0,370365,15.5000,Q
187,188,1,1,male,45.00,0,0,111428,26.5500,S
188,189,0,3,male,40.00,1,1,364849,15.5000,Q
189,190,0,3,male,36.00,0,0,349247,7.8958,S
190,191,1,2,female,32.00,0,0,234604,13.0000,S
191,192,0,2,male,19.00,0,0,28424,13.0000,S
192,193,1,3,female,19.00,1,0,350046,7.8542,S
193,194,1,2,male,3.00,1,1,230080,26.0000,S
194,195,1,1,female,44.00,0,0,PC 17610,27.7208,C
195,196,1,1,female,58.00,0,0,PC 17569,146.5208,C
196,197,0,3,male,NaN,0,0,368703,7.7500,Q
197,198,0,3,male,42.00,0,1,4579,8.4042,S
198,199,1,3,female,NaN,0,0,370370,7.7500,Q
199,200,0,2,female,24.00,0,0,248747,13.0000,S
200,201,0,3,male,28.00,0,0,345770,9.5000,S
201,202,0,3,male,NaN,8,2,CA. 2343,69.5500,S
202,203,0,3,male,34.00,0,0,3101264,6.4958,S
203,204,0,3,male,45.50,0,0,2628,7.2250,C
204,205,1,3,male,18.00,0,0,A/5 3540,8.0500,S
205,206,0,3,female,2.00,0,1,347054,10.4625,S
206,207,0,3,male,32.00,1,0,3101278,15.8500,S
207,208,1,3,male,26.00,0,0,2699,18.7875,C
208,209,1,3,female,16.00,0,0,367231,7.7500,Q
209,210,1,1,male,40.00,0,0,112277,31.0000,C
210,211,0,3,male,24.00,0,0,SOTON/O.Q. 3101311,7.0500,S
211,212,1,2,female,35.00,0,0,F.C.C. 13528,21.0000,S
212,213,0,3,male,22.00,0,0,A/5 21174,7.2500,S
213,214,0,2,male,30.00,0,0,250646,13.0000,S
214,215,0,3,male,NaN,1,0,367229,7.7500,Q
215,216,1,1,female,31.00,1,0,35273,113.2750,C
216,217,1,3,female,27.00,0,0,STON/O2. 3101283,7.9250,S
217,218,0,2,male,42.00,1,0,243847,27.0000,S
218,219,1,1,female,32.00,0,0,11813,76.2917,C
219,220,0,2,male,30.00,0,0,W/C 14208,10.5000,S
220,221,1,3,male,16.00,0,0,SOTON/OQ 392089,8.0500,S
221,222,0,2,male,27.00,0,0,220367,13.0000,S
222,223,0,3,male,51.00,0,0,21440,8.0500,S
223,224,0,3,male,NaN,0,0,349234,7.8958,S
224,225,1,1,male,38.00,1,0,19943,90.0000,S
225,226,0,3,male,22.00,0,0,PP 4348,9.3500,S
226,227,1,2,male,19.00,0,0,SW/PP 751,10.5000,S
227,228,0,3,male,20.50,0,0,A/5 21173,7.2500,S
228,229,0,2,male,18.00,0,0,236171,13.0000,S
229,230,0,3,female,NaN,3,1,4133,25.4667,S
230,231,1,1,female,35.00,1,0,36973,83.4750,S
231,232,0,3,male,29.00,0,0,347067,7.7750,S
232,233,0,2,male,59.00,0,0,237442,13.5000,S
233,234,1,3,female,5.00,4,2,347077,31.3875,S
234,235,0,2,male,24.00,0,0,C.A. 29566,10.5000,S
235,236,0,3,female,NaN,0,0,W./C. 6609,7.5500,S
236,237,0,2,male,44.00,1,0,26707,26.0000,S
237,238,1,2,female,8.00,0,2,C.A. 31921,26.2500,S
238,239,0,2,male,19.00,0,0,28665,10.5000,S
239,240,0,2,male,33.00,0,0,SCO/W 1585,12.2750,S
240,241,0,3,female,NaN,1,0,2665,14.4542,C
241,242,1,3,female,NaN,1,0,367230,15.5000,Q
242,243,0,2,male,29.00,0,0,W./C. 14263,10.5000,S
243,244,0,3,male,22.00,0,0,STON/O 2. 3101275,7.1250,S
244,245,0,3,male,30.00,0,0,2694,7.2250,C
245,246,0,1,male,44.00,2,0,19928,90.0000,Q
246,247,0,3,female,25.00,0,0,347071,7.7750,S
247,248,1,2,female,24.00,0,2,250649,14.5000,S
248,249,1,1,male,37.00,1,1,11751,52.5542,S
249,250,0,2,male,54.00,1,0,244252,26.0000,S
250,251,0,3,male,NaN,0,0,362316,7.2500,S
251,252,0,3,female,29.00,1,1,347054,10.4625,S
252,253,0,1,male,62.00,0,0,113514,26.5500,S
253,254,0,3,male,30.00,1,0,A/5. 3336,16.1000,S
254,255,0,3,female,41.00,0,2,370129,20.2125,S
255,256,1,3,female,29.00,0,2,2650,15.2458,C
256,257,1,1,female,NaN,0,0,PC 17585,79.2000,C
257,258,1,1,female,30.00,0,0,110152,86.5000,S
258,259,1,1,female,35.00,0,0,PC 17755,512.3292,C
259,260,1,2,female,50.00,0,1,230433,26.0000,S
260,261,0,3,male,NaN,0,0,384461,7.7500,Q
261,262,1,3,male,3.00,4,2,347077,31.3875,S
262,263,0,1,male,52.00,1,1,110413,79.6500,S
263,264,0,1,male,40.00,0,0,112059,0.0000,S
264,265,0,3,female,NaN,0,0,382649,7.7500,Q
265,266,0,2,male,36.00,0,0,C.A. 17248,10.5000,S
266,267,0,3,male,16.00,4,1,3101295,39.6875,S
267,268,1,3,male,25.00,1,0,347083,7.7750,S
268,269,1,1,female,58.00,0,1,PC 17582,153.4625,S
269,270,1,1,female,35.00,0,0,PC 17760,135.6333,S
270,271,0,1,male,NaN,0,0,113798,31.0000,S
271,272,1,3,male,25.00,0,0,LINE,0.0000,S
272,273,1,2,female,41.00,0,1,250644,19.5000,S
273,274,0,1,male,37.00,0,1,PC 17596,29.7000,C
274,275,1,3,female,NaN,0,0,370375,7.7500,Q
275,276,1,1,female,63.00,1,0,13502,77.9583,S
276,277,0,3,female,45.00,0,0,347073,7.7500,S
277,278,0,2,male,NaN,0,0,239853,0.0000,S
278,279,0,3,male,7.00,4,1,382652,29.1250,Q
279,280,1,3,female,35.00,1,1,C.A. 2673,20.2500,S
280,281,0,3,male,65.00,0,0,336439,7.7500,Q
281,282,0,3,male,28.00,0,0,347464,7.8542,S
282,283,0,3,male,16.00,0,0,345778,9.5000,S
283,284,1,3,male,19.00,0,0,A/5. 10482,8.0500,S
284,285,0,1,male,NaN,0,0,113056,26.0000,S
285,286,0,3,male,33.00,0,0,349239,8.6625,C
286,287,1,3,male,30.00,0,0,345774,9.5000,S
287,288,0,3,male,22.00,0,0,349206,7.8958,S
288,289,1,2,male,42.00,0,0,237798,13.0000,S
289,290,1,3,female,22.00,0,0,370373,7.7500,Q
290,291,1,1,female,26.00,0,0,19877,78.8500,S
291,292,1,1,female,19.00,1,0,11967,91.0792,C
292,293,0,2,male,36.00,0,0,SC/Paris 2163,12.8750,C
293,294,0,3,female,24.00,0,0,349236,8.8500,S
294,295,0,3,male,24.00,0,0,349233,7.8958,S
295,296,0,1,male,NaN,0,0,PC 17612,27.7208,C
296,297,0,3,male,23.50,0,0,2693,7.2292,C
297,298,0,1,female,2.00,1,2,113781,151.5500,S
298,299,1,1,male,NaN,0,0,19988,30.5000,S
299,300,1,1,female,50.00,0,1,PC 17558,247.5208,C
300,301,1,3,female,NaN,0,0,9234,7.7500,Q
301,302,1,3,male,NaN,2,0,367226,23.2500,Q
302,303,0,3,male,19.00,0,0,LINE,0.0000,S
303,304,1,2,female,NaN,0,0,226593,12.3500,Q
304,305,0,3,male,NaN,0,0,A/5 2466,8.0500,S
305,306,1,1,male,0.92,1,2,113781,151.5500,S
306,307,1,1,female,NaN,0,0,17421,110.8833,C
307,308,1,1,female,17.00,1,0,PC 17758,108.9000,C
308,309,0,2,male,30.00,1,0,P/PP 3381,24.0000,C
309,310,1,1,female,30.00,0,0,PC 17485,56.9292,C
310,311,1,1,female,24.00,0,0,11767,83.1583,C
311,312,1,1,female,18.00,2,2,PC 17608,262.3750,C
312,313,0,2,female,26.00,1,1,250651,26.0000,S
313,314,0,3,male,28.00,0,0,349243,7.8958,S
314,315,0,2,male,43.00,1,1,F.C.C. 13529,26.2500,S
315,316,1,3,female,26.00,0,0,347470,7.8542,S
316,317,1,2,female,24.00,1,0,244367,26.0000,S
317,318,0,2,male,54.00,0,0,29011,14.0000,S
318,319,1,1,female,31.00,0,2,36928,164.8667,S
319,320,1,1,female,40.00,1,1,16966,134.5000,C
320,321,0,3,male,22.00,0,0,A/5 21172,7.2500,S
321,322,0,3,male,27.00,0,0,349219,7.8958,S
322,323,1,2,female,30.00,0,0,234818,12.3500,Q
323,324,1,2,female,22.00,1,1,248738,29.0000,S
324,325,0,3,male,NaN,8,2,CA. 2343,69.5500,S
325,326,1,1,female,36.00,0,0,PC 17760,135.6333,C
326,327,0,3,male,61.00,0,0,345364,6.2375,S
327,328,1,2,female,36.00,0,0,28551,13.0000,S
328,329,1,3,female,31.00,1,1,363291,20.5250,S
329,330,1,1,female,16.00,0,1,111361,57.9792,C
330,331,1,3,female,NaN,2,0,367226,23.2500,Q
331,332,0,1,male,45.50,0,0,113043,28.5000,S
332,333,0,1,male,38.00,0,1,PC 17582,153.4625,S
333,334,0,3,male,16.00,2,0,345764,18.0000,S
334,335,1,1,female,NaN,1,0,PC 17611,133.6500,S
335,336,0,3,male,NaN,0,0,349225,7.8958,S
336,337,0,1,male,29.00,1,0,113776,66.6000,S
337,338,1,1,female,41.00,0,0,16966,134.5000,C
338,339,1,3,male,45.00,0,0,7598,8.0500,S
339,340,0,1,male,45.00,0,0,113784,35.5000,S
340,341,1,2,male,2.00,1,1,230080,26.0000,S
341,342,1,1,female,24.00,3,2,19950,263.0000,S
342,343,0,2,male,28.00,0,0,248740,13.0000,S
343,344,0,2,male,25.00,0,0,244361,13.0000,S
344,345,0,2,male,36.00,0,0,229236,13.0000,S
345,346,1,2,female,24.00,0,0,248733,13.0000,S
346,347,1,2,female,40.00,0,0,31418,13.0000,S
347,348,1,3,female,NaN,1,0,386525,16.1000,S
348,349,1,3,male,3.00,1,1,C.A. 37671,15.9000,S
349,350,0,3,male,42.00,0,0,315088,8.6625,S
350,351,0,3,male,23.00,0,0,7267,9.2250,S
351,352,0,1,male,NaN,0,0,113510,35.0000,S
352,353,0,3,male,15.00,1,1,2695,7.2292,C
353,354,0,3,male,25.00,1,0,349237,17.8000,S
354,355,0,3,male,NaN,0,0,2647,7.2250,C
355,356,0,3,male,28.00,0,0,345783,9.5000,S
356,357,1,1,female,22.00,0,1,113505,55.0000,S
357,358,0,2,female,38.00,0,0,237671,13.0000,S
358,359,1,3,female,NaN,0,0,330931,7.8792,Q
359,360,1,3,female,NaN,0,0,330980,7.8792,Q
360,361,0,3,male,40.00,1,4,347088,27.9000,S
361,362,0,2,male,29.00,1,0,SC/PARIS 2167,27.7208,C
362,363,0,3,female,45.00,0,1,2691,14.4542,C
363,364,0,3,male,35.00,0,0,SOTON/O.Q. 3101310,7.0500,S
364,365,0,3,male,NaN,1,0,370365,15.5000,Q
365,366,0,3,male,30.00,0,0,C 7076,7.2500,S
366,367,1,1,female,60.00,1,0,110813,75.2500,C
367,368,1,3,female,NaN,0,0,2626,7.2292,C
368,369,1,3,female,NaN,0,0,14313,7.7500,Q
369,370,1,1,female,24.00,0,0,PC 17477,69.3000,C
370,371,1,1,male,25.00,1,0,11765,55.4417,C
371,372,0,3,male,18.00,1,0,3101267,6.4958,S
372,373,0,3,male,19.00,0,0,323951,8.0500,S
373,374,0,1,male,22.00,0,0,PC 17760,135.6333,C
374,375,0,3,female,3.00,3,1,349909,21.0750,S
375,376,1,1,female,NaN,1,0,PC 17604,82.1708,C
376,377,1,3,female,22.00,0,0,C 7077,7.2500,S
377,378,0,1,male,27.00,0,2,113503,211.5000,C
378,379,0,3,male,20.00,0,0,2648,4.0125,C
379,380,0,3,male,19.00,0,0,347069,7.7750,S
380,381,1,1,female,42.00,0,0,PC 17757,227.5250,C
381,382,1,3,female,1.00,0,2,2653,15.7417,C
382,383,0,3,male,32.00,0,0,STON/O 2. 3101293,7.9250,S
383,384,1,1,female,35.00,1,0,113789,52.0000,S
384,385,0,3,male,NaN,0,0,349227,7.8958,S
385,386,0,2,male,18.00,0,0,S.O.C. 14879,73.5000,S
386,387,0,3,male,1.00,5,2,CA 2144,46.9000,S
387,388,1,2,female,36.00,0,0,27849,13.0000,S
388,389,0,3,male,NaN,0,0,367655,7.7292,Q
389,390,1,2,female,17.00,0,0,SC 1748,12.0000,C
390,391,1,1,male,36.00,1,2,113760,120.0000,S
391,392,1,3,male,21.00,0,0,350034,7.7958,S
392,393,0,3,male,28.00,2,0,3101277,7.9250,S
393,394,1,1,female,23.00,1,0,35273,113.2750,C
394,395,1,3,female,24.00,0,2,PP 9549,16.7000,S
395,396,0,3,male,22.00,0,0,350052,7.7958,S
396,397,0,3,female,31.00,0,0,350407,7.8542,S
397,398,0,2,male,46.00,0,0,28403,26.0000,S
398,399,0,2,male,23.00,0,0,244278,10.5000,S
399,400,1,2,female,28.00,0,0,240929,12.6500,S
400,401,1,3,male,39.00,0,0,STON/O 2. 3101289,7.9250,S
401,402,0,3,male,26.00,0,0,341826,8.0500,S
402,403,0,3,female,21.00,1,0,4137,9.8250,S
403,404,0,3,male,28.00,1,0,STON/O2. 3101279,15.8500,S
404,405,0,3,female,20.00,0,0,315096,8.6625,S
405,406,0,2,male,34.00,1,0,28664,21.0000,S
406,407,0,3,male,51.00,0,0,347064,7.7500,S
407,408,1,2,male,3.00,1,1,29106,18.7500,S
408,409,0,3,male,21.00,0,0,312992,7.7750,S
409,410,0,3,female,NaN,3,1,4133,25.4667,S
410,411,0,3,male,NaN,0,0,349222,7.8958,S
411,412,0,3,male,NaN,0,0,394140,6.8583,Q
412,413,1,1,female,33.00,1,0,19928,90.0000,Q
413,414,0,2,male,NaN,0,0,239853,0.0000,S
414,415,1,3,male,44.00,0,0,STON/O 2. 3101269,7.9250,S
415,416,0,3,female,NaN,0,0,343095,8.0500,S
416,417,1,2,female,34.00,1,1,28220,32.5000,S
417,418,1,2,female,18.00,0,2,250652,13.0000,S
418,419,0,2,male,30.00,0,0,28228,13.0000,S
419,420,0,3,female,10.00,0,2,345773,24.1500,S
420,421,0,3,male,NaN,0,0,349254,7.8958,C
421,422,0,3,male,21.00,0,0,A/5. 13032,7.7333,Q
422,423,0,3,male,29.00,0,0,315082,7.8750,S
423,424,0,3,female,28.00,1,1,347080,14.4000,S
424,425,0,3,male,18.00,1,1,370129,20.2125,S
425,426,0,3,male,NaN,0,0,A/4. 34244,7.2500,S
426,427,1,2,female,28.00,1,0,2003,26.0000,S
427,428,1,2,female,19.00,0,0,250655,26.0000,S
428,429,0,3,male,NaN,0,0,364851,7.7500,Q
429,430,1,3,male,32.00,0,0,SOTON/O.Q. 392078,8.0500,S
430,431,1,1,male,28.00,0,0,110564,26.5500,S
431,432,1,3,female,NaN,1,0,376564,16.1000,S
432,433,1,2,female,42.00,1,0,SC/AH 3085,26.0000,S
433,434,0,3,male,17.00,0,0,STON/O 2. 3101274,7.1250,S
434,435,0,1,male,50.00,1,0,13507,55.9000,S
435,436,1,1,female,14.00,1,2,113760,120.0000,S
436,437,0,3,female,21.00,2,2,W./C. 6608,34.3750,S
437,438,1,2,female,24.00,2,3,29106,18.7500,S
438,439,0,1,male,64.00,1,4,19950,263.0000,S
439,440,0,2,male,31.00,0,0,C.A. 18723,10.5000,S
440,441,1,2,female,45.00,1,1,F.C.C. 13529,26.2500,S
441,442,0,3,male,20.00,0,0,345769,9.5000,S
442,443,0,3,male,25.00,1,0,347076,7.7750,S
443,444,1,2,female,28.00,0,0,230434,13.0000,S
444,445,1,3,male,NaN,0,0,65306,8.1125,S
445,446,1,1,male,4.00,0,2,33638,81.8583,S
446,447,1,2,female,13.00,0,1,250644,19.5000,S
447,448,1,1,male,34.00,0,0,113794,26.5500,S
448,449,1,3,female,5.00,2,1,2666,19.2583,C

In [64]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 20

In [65]:
train2['Age'].isnull().sum()

177

In [66]:
train2['Age'].notnull().sum()

714

In [67]:
train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [68]:
train2[train2['Age'].isnull()]

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
5,6,0,3,male,NaN,0,0,330877,8.4583,Q
17,18,1,2,male,NaN,0,0,244373,13.0000,S
19,20,1,3,female,NaN,0,0,2649,7.2250,C
26,27,0,3,male,NaN,0,0,2631,7.2250,C
28,29,1,3,female,NaN,0,0,330959,7.8792,Q
...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,male,NaN,0,0,2629,7.2292,C
863,864,0,3,female,NaN,8,2,CA. 2343,69.5500,S
868,869,0,3,male,NaN,0,0,345777,9.5000,S
878,879,0,3,male,NaN,0,0,349217,7.8958,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,S

In [69]:
train2[train2['Age'].notnull()].count()

PassengerId    714
Survived       714
Pclass         714
Sex            714
Age            714
SibSp          714
Parch          714
Ticket         714
Fare           714
Embarked       712
dtype: int64

In [70]:
train_age = train2.sort_values(by='Age', ascending=False)
train_age

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
630,631,1,1,male,80.0,0,0,27042,30.0000,S
851,852,0,3,male,74.0,0,0,347060,7.7750,S
493,494,0,1,male,71.0,0,0,PC 17609,49.5042,C
96,97,0,1,male,71.0,0,0,PC 17754,34.6542,C
116,117,0,3,male,70.5,0,0,370369,7.7500,Q
...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,male,NaN,0,0,2629,7.2292,C
863,864,0,3,female,NaN,8,2,CA. 2343,69.5500,S
868,869,0,3,male,NaN,0,0,345777,9.5000,S
878,879,0,3,male,NaN,0,0,349217,7.8958,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,S

In [71]:
train_age.reset_index()

,index,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,630,631,1,1,male,80.0,0,0,27042,30.0000,S
1,851,852,0,3,male,74.0,0,0,347060,7.7750,S
2,493,494,0,1,male,71.0,0,0,PC 17609,49.5042,C
3,96,97,0,1,male,71.0,0,0,PC 17754,34.6542,C
4,116,117,0,3,male,70.5,0,0,370369,7.7500,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,859,860,0,3,male,NaN,0,0,2629,7.2292,C
887,863,864,0,3,female,NaN,8,2,CA. 2343,69.5500,S
888,868,869,0,3,male,NaN,0,0,345777,9.5000,S
889,878,879,0,3,male,NaN,0,0,349217,7.8958,S
890,888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,S

In [72]:
train_age

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
630,631,1,1,male,80.0,0,0,27042,30.0000,S
851,852,0,3,male,74.0,0,0,347060,7.7750,S
493,494,0,1,male,71.0,0,0,PC 17609,49.5042,C
96,97,0,1,male,71.0,0,0,PC 17754,34.6542,C
116,117,0,3,male,70.5,0,0,370369,7.7500,Q
...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,male,NaN,0,0,2629,7.2292,C
863,864,0,3,female,NaN,8,2,CA. 2343,69.5500,S
868,869,0,3,male,NaN,0,0,345777,9.5000,S
878,879,0,3,male,NaN,0,0,349217,7.8958,S
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500,S

In [73]:
print(len(train_age.reset_index().columns), train_age.reset_index().columns)

11 Index(['index', 'PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [74]:
print(len(train_age.columns), train_age.columns)

10 Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [75]:
train_age.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 630 to 888
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(3)
memory usage: 76.6+ KB

#### [데이터셋]['col'].unique() : 데이터셋에서 'col'열의 유일한 값만 골라낸다.

In [76]:
train_age['SibSp'].unique()

array([0, 1, 2, 3, 4, 5, 8], dtype=int64)

#### [데이터셋]['col'].value_counts() : 데이터셋에서 'col'열의 유일한 값별로 개수를 센다.

In [77]:
train_age['SibSp'].value_counts()

0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64

In [78]:
train_age['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [79]:
train_age['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64