In [7]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time

In [8]:
driver = webdriver.Chrome('chromedriver_94')

url = 'https://coronaboard.kr/'
driver.get(url)
time.sleep(3)

### 더보기 버튼 2번 클릭해서 화면 전체 보기

In [9]:
# 더보기 버튼(1번째)
from selenium.webdriver import ActionChains

some_tag = driver.find_element_by_id('show-more')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

In [10]:
# 더보기 버튼(2번째)
some_tag = driver.find_element_by_id('show-more')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

### 여러 옵션 선택

In [11]:
# 옵션 버튼
some_tag = driver.find_element_by_xpath('//*[@id="global-slide"]/div/div[2]/div/div/button/div/div/div')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

In [12]:
# 위중증 옵션 선택
sel_menu = driver.find_element_by_xpath('//*[@id="bs-select-1-1"]')
sel_menu.click()

In [13]:
# 인구수 옵션 선택
sel_menu = driver.find_element_by_xpath('//*[@id="bs-select-1-5"]')
sel_menu.click()

## 데이터 만들기

In [14]:
# 여러 국가명 가져오기
sel_country = driver.find_elements_by_xpath('//*[@id="country-table"]/div/div/table/tbody/tr/td[2]')
len(sel_country)

222

In [15]:
# 여러 국가명 확인
for one in sel_country:
    print(one.text)

미국🇺🇸
인도🇮🇳
브라질🇧🇷
영국🇬🇧
러시아🇷🇺
터키🇹🇷
프랑스🇫🇷
이란🇮🇷
아르헨티나🇦🇷
콜롬비아🇨🇴
스페인🇪🇸
이탈리아🇮🇹
독일🇩🇪
인도네시아🇮🇩
멕시코🇲🇽
폴란드🇵🇱
남아프리카 공화국🇿🇦
필리핀🇵🇭
우크라이나🇺🇦
말레이시아🇲🇾
페루🇵🇪
네덜란드🇳🇱
이라크🇮🇶
일본🇯🇵*
체코🇨🇿
칠레🇨🇱
캐나다🇨🇦
태국🇹🇭
방글라데시🇧🇩
이스라엘🇮🇱
파키스탄🇵🇰
벨기에🇧🇪
루마니아🇷🇴
스웨덴🇸🇪
포르투갈🇵🇹
모로코🇲🇦
세르비아🇷🇸
카자흐스탄🇰🇿
쿠바🇨🇺
스위스🇨🇭
요르단🇯🇴
헝가리🇭🇺
네팔🇳🇵
베트남🇻🇳
오스트리아🇦🇹
아랍에미레이트🇦🇪
튀니지🇹🇳
그리스🇬🇷
레바논🇱🇧
조지아🇬🇪
과테말라🇬🇹
사우디아라비아🇸🇦
벨라루스🇧🇾
코스타리카🇨🇷
스리랑카🇱🇰
에콰도르🇪🇨
볼리비아🇧🇴
불가리아🇧🇬
아제르바이잔🇦🇿
파나마🇵🇦
미얀마🇲🇲
파라과이🇵🇾
쿠웨이트🇰🇼
슬로바키아🇸🇰
크로아티아🇭🇷
팔레스타인🇵🇸
우루과이🇺🇾
아일랜드🇮🇪
베네수엘라🇻🇪
온두라스🇭🇳
도미니카 공화국🇩🇴
덴마크🇩🇰
에티오피아🇪🇹
리비아🇱🇾
리투아니아🇱🇹
대한민국🇰🇷
오만🇴🇲
이집트🇪🇬
몽골🇲🇳
몰도바🇲🇩
슬로베니아🇸🇮
바레인🇧🇭
아르메니아🇦🇲
케냐🇰🇪
카타르🇶🇦
보스니아 헤르체고비나🇧🇦
잠비아🇿🇲
나이지리아🇳🇬
알제리🇩🇿
북마케도니아🇲🇰
노르웨이🇳🇴
키르기스스탄🇰🇬
보츠와나🇧🇼
우즈베키스탄🇺🇿
알바니아🇦🇱
라트비아🇱🇻
아프가니스탄🇦🇫
에스토니아🇪🇪
모잠비크🇲🇿
핀란드🇫🇮
몬테네그로🇲🇪
짐바브웨🇿🇼
나미비아🇳🇦
가나🇬🇭
우간다🇺🇬
키프로스🇨🇾
캄보디아🇰🇭
코소보🇽🇰
엘살바도르🇸🇻
호주🇦🇺
르완다🇷🇼
중국🇨🇳
싱가포르🇸🇬
카메룬🇨🇲
몰디브🇲🇻
자메이카🇯🇲
룩셈부르크🇱🇺
세네갈🇸🇳
말라위🇲🇼
코트디부아르🇨🇮
콩고민주공화국🇨🇩
앙골라🇦🇴
레위니옹🇷🇪
과들루프🇬🇵
피지🇫🇯
트리니다드 토바고🇹🇹
에스와티니🇸🇿
마다가스카르🇲🇬
수리남🇸🇷
프랑스령 기아나🇬🇫
마르티니크🇲🇶
프랑스령 폴리네시아🇵🇫
수단🇸🇩
카보베르데🇨🇻
몰타 공화국🇲🇹
모리타니🇲🇷
시리아🇸🇾
가이아나🇬🇾
기니🇬🇳
가봉🇬🇦
토고🇹🇬
베냉🇧🇯
라오스🇱🇦
아이티🇭🇹
세이셸🇸🇨
바하마🇧🇸
벨리즈🇧🇿
마요트🇾🇹
소말리아🇸🇴
파푸아뉴기니🇵🇬
동티모르🇹🇱
부룬디🇧🇮
타지키스탄🇹🇯
퀴라소🇨🇼
대만🇹🇼
아루바🇦🇼
모리셔스🇲🇺
안도라🇦🇩
말리🇲🇱
니카라과🇳🇮
레소토🇱🇸
콩고공화국🇨🇬
부르키나파소🇧🇫
지부티🇩🇯
홍콩🇭🇰
남수단🇸🇸
적도 기니🇬🇶
아이슬란드🇮🇸
중앙아프리카 공화국🇨🇫
세인트루시아🇱🇨
감비아🇬🇲
예멘🇾🇪
바베이도스🇧🇧
맨섬🇮🇲
뉴칼레도니아🇳🇨
브루나이🇧🇳
에리트레아🇪🇷
시에라리온🇸🇱
기니비사우🇬🇼
니제르🇳🇪
라이베리아🇱🇷
지브롤터🇬🇮
산마리노🇸🇲
버뮤다🇧🇲
그레나다🇬🇩
차드🇹🇩
신트마르턴🇸🇽
뉴질랜드🇳🇿
코모로🇰🇲
세인트마틴 섬🇲🇫
리히텐슈타인🇱🇮
상투메 프린시페🇸🇹
세인트빈센트 그레나딘🇻🇨
모나코🇲🇨
도미니카 연방🇩🇲
앤티가 바부다🇦🇬
터크스 케이커스 제도🇹🇨
영국령 버진아일랜드🇻🇬
부탄🇧🇹
카리브 네덜란드🇧🇶
세인트키츠 네비스🇰🇳
생바르텔레미🇧🇱
탄자니아🇹🇿
페로 제도🇫🇴
케이맨 제도🇰🇾
그린란드🇬🇱
왈리스 퓌티나🇼🇫
앵귈라🇦🇮
마카오🇲🇴
포클랜드 제도🇫🇰
몬트세랫🇲🇸
생피에르 미클롱🇵🇲
바티칸 시국🇻🇦
솔로몬 제도🇸🇧
서사하라🇪🇭
잔담(크루즈)🚢
팔라우🇵🇼
마셜 제도🇲🇭
바누아투🇻🇺
사모아🇼🇸
세인트헬레나🇸🇭
미크로네시아🇫🇲

### 어제 탭 선택하기

In [16]:
# 어제 : //*[@id="global-slide"]/div/div[2]/ul/li[2]/a
flag_today = False # False : 어제, Today : 오늘

In [17]:
if flag_today==False:
    sel_yesterday = driver.find_element_by_xpath('//*[@id="global-slide"]/div/div[2]/ul/li[2]/a')
    sel_yesterday.click()

### 항목 별로 리스트 만들어 리스트로 만들기

In [18]:
all_data = []
for i in range(2, 11):
    tmp = '//*[@id="country-table"]/div/div/table/tbody/tr/td[{}]'.format(i)
    # print(tmp)
    sel_ele = driver.find_elements_by_xpath(tmp)
    
    
    column_data = []
    for one in sel_ele:
        # print(one.text)
        column_data.append(one.text)
    
    print( len(sel_ele) )
    all_data.append(column_data)
    print(column_data)
    print()
    
all_data

222
['미국🇺🇸', '인도🇮🇳', '브라질🇧🇷', '영국🇬🇧', '러시아🇷🇺', '터키🇹🇷', '프랑스🇫🇷', '이란🇮🇷', '아르헨티나🇦🇷', '콜롬비아🇨🇴', '스페인🇪🇸', '이탈리아🇮🇹', '독일🇩🇪', '인도네시아🇮🇩', '멕시코🇲🇽', '폴란드🇵🇱', '남아프리카 공화국🇿🇦', '필리핀🇵🇭', '우크라이나🇺🇦', '말레이시아🇲🇾', '페루🇵🇪', '네덜란드🇳🇱', '이라크🇮🇶', '일본🇯🇵*', '체코🇨🇿', '칠레🇨🇱', '캐나다🇨🇦', '태국🇹🇭', '방글라데시🇧🇩', '이스라엘🇮🇱', '파키스탄🇵🇰', '벨기에🇧🇪', '루마니아🇷🇴', '스웨덴🇸🇪', '포르투갈🇵🇹', '모로코🇲🇦', '세르비아🇷🇸', '카자흐스탄🇰🇿', '쿠바🇨🇺', '스위스🇨🇭', '헝가리🇭🇺', '요르단🇯🇴', '네팔🇳🇵', '베트남🇻🇳', '오스트리아🇦🇹', '아랍에미레이트🇦🇪', '튀니지🇹🇳', '그리스🇬🇷', '레바논🇱🇧', '조지아🇬🇪', '과테말라🇬🇹', '사우디아라비아🇸🇦', '벨라루스🇧🇾', '코스타리카🇨🇷', '스리랑카🇱🇰', '에콰도르🇪🇨', '볼리비아🇧🇴', '불가리아🇧🇬', '아제르바이잔🇦🇿', '파나마🇵🇦', '파라과이🇵🇾', '미얀마🇲🇲', '쿠웨이트🇰🇼', '슬로바키아🇸🇰', '크로아티아🇭🇷', '팔레스타인🇵🇸', '우루과이🇺🇾', '아일랜드🇮🇪', '베네수엘라🇻🇪', '온두라스🇭🇳', '덴마크🇩🇰', '도미니카 공화국🇩🇴', '에티오피아🇪🇹', '리비아🇱🇾', '리투아니아🇱🇹', '대한민국🇰🇷', '오만🇴🇲', '이집트🇪🇬', '몽골🇲🇳', '슬로베니아🇸🇮', '몰도바🇲🇩', '바레인🇧🇭', '아르메니아🇦🇲', '케냐🇰🇪', '카타르🇶🇦', '보스니아 헤르체고비나🇧🇦', '잠비아🇿🇲', '나이지리아🇳🇬', '알제리🇩🇿', '북마케도니아🇲🇰', '노르웨이🇳🇴', '키르기스스탄🇰🇬', '보츠와나🇧🇼', '우즈베키스탄🇺🇿', '알바니아🇦🇱', '라트비아🇱🇻', '아프가니스탄🇦🇫', '에스토니아🇪🇪', '모잠비크🇲🇿', '핀란드🇫🇮', '몬테네그로🇲🇪', '짐바브웨🇿🇼', '나미비아🇳🇦', '가나🇬🇭', '우간다🇺🇬', '키프로스🇨🇾', '캄보디아🇰🇭', '코소보🇽🇰', '엘살바도르🇸🇻', '호주🇦🇺', '르완다🇷🇼', '중국🇨🇳', '싱가포르🇸🇬', '카메룬🇨🇲', '몰디브🇲🇻', '자메이카🇯🇲', '룩셈부르크🇱🇺', '세네갈🇸🇳', '말라위🇲🇼', '코트디부아르🇨🇮', '콩고민주공화국🇨🇩', '앙골라🇦🇴', '레위니옹🇷🇪', '과들루프🇬🇵', '피지🇫🇯', '트리니다드 토바고🇹🇹', '에스와티니🇸🇿', '마다가스카르🇲🇬', '마르티니크🇲🇶', '수리남🇸🇷', '프랑스령 폴리네시아🇵🇫', '프랑스령 기아나🇬🇫', '수단🇸🇩', '카보베르데🇨🇻', '몰타 공화국🇲🇹', '모리타니🇲🇷', '시리아🇸🇾', '가이아나🇬🇾', '기니🇬🇳', '가봉🇬🇦', '토고🇹🇬', '베냉🇧🇯', '라오스🇱🇦', '아이티🇭🇹', '세이셸🇸🇨', '바하마🇧🇸', '마요트🇾🇹', '소말리아🇸🇴', '벨리즈🇧🇿', '파푸아뉴기니🇵🇬', '동티모르🇹🇱', '부룬디🇧🇮', '타지키스탄🇹🇯', '퀴라소🇨🇼', '대만🇹🇼', '아루바🇦🇼', '모리셔스🇲🇺', '안도라🇦🇩', '말리🇲🇱', '레소토🇱🇸', '콩고공화국🇨🇬', '부르키나파소🇧🇫', '니카라과🇳🇮', '지부티🇩🇯', '홍콩🇭🇰', '남수단🇸🇸', '적도 기니🇬🇶', '아이슬란드🇮🇸', '중앙아프리카 공화국🇨🇫', '세인트루시아🇱🇨', '감비아🇬🇲', '예멘🇾🇪', '바베이도스🇧🇧', '맨섬🇮🇲', '뉴칼레도니아🇳🇨', '브루나이🇧🇳', '에리트레아🇪🇷', '시에라리온🇸🇱', '기니비사우🇬🇼', '니제르🇳🇪', '라이베리아🇱🇷', '지브롤터🇬🇮', '산마리노🇸🇲', '버뮤다🇧🇲', '차드🇹🇩', '그레나다🇬🇩', '신트마르턴🇸🇽', '뉴질랜드🇳🇿', '코모로🇰🇲', '세인트마틴 섬🇲🇫', '리히텐슈타인🇱🇮', '세인트빈센트 그레나딘🇻🇨', '상투메 프린시페🇸🇹', '모나코🇲🇨', '도미니카 연방🇩🇲', '앤티가 바부다🇦🇬', '터크스 케이커스 제도🇹🇨', '영국령 버진아일랜드🇻🇬', '부탄🇧🇹', '카리브 네덜란드🇧🇶', '세인트키츠 네비스🇰🇳', '생바르텔레미🇧🇱', '탄자니아🇹🇿', '페로 제도🇫🇴', '케이맨 제도🇰🇾', '그린란드🇬🇱', '왈리스 퓌티나🇼🇫', '앵귈라🇦🇮', '마카오🇲🇴', '포클랜드 제도🇫🇰', '몬트세랫🇲🇸', '생피에르 미클롱🇵🇲', '바티칸 시국🇻🇦', '솔로몬 제도🇸🇧', '서사하라🇪🇭', '잔담(크루즈)🚢', '팔라우🇵🇼', '마셜 제도🇲🇭', '바누아투🇻🇺', '사모아🇼🇸', '세인트헬레나🇸🇭', '미크로네시아🇫🇲']

222
['43,942,335\n(+187,382)', '33,714,241\n(+21,093)', '21,366,395\n(+14,423)', '7,701,715\n(+37,485)', '7,464,708\n(+21,559)', '7,066,688\n(+27,188)', '6,995,628\n(+1,309)', '5,559,691\n(+11,701)', '5,251,940\n(+1,538)', '4,952,690\n(+1,015)', '4,951,640\n(+5,039)', '4,662,087\n(+1,773)', '4,212,201\n(+4,941)', '4,211,460\n(+2,057)', '3,635,807\n(+3,007)', '2,904,631\n(+976)', '2,897,521\n(+578)', '2,522,965\n(+32,107)', '2,401,956\n(+6,552)', '2,209,194\n(+10,959)', '2,173,354\n(+320)', '1,999,592\n(+1,707)', '1,998,615\n(+2,401)', '1,698,344\n(+1,722)', '1,690,288\n(+668)', '1,652,795\n(+431)', '1,612,431\n(+10,052)', '1,581,415\n(+9,489)', '1,553,873\n(+1,310)', '1,270,230', '1,241,825\n(+1,400)', '1,238,358\n(+4,635)', '1,210,810\n(+11,049)', '1,151,173\n(+1,766)', '1,067,775\n(+600)', '929,699\n(+394)', '926,269\n(+8,467)', '880,709\n(+1,719)', '866,808\n(+6,009)', '837,767\n(+1,288)', '821,526\n(+265)', '820,798\n(+1,015)', '793,271\n(+904)', '770,640\n(+4,589)', '738,763\n(+1,561)', '735,457\n(+277)', '705,474\n(+179)', '648,091\n(+2,122)', '622,440\n(+205)', '609,340\n(+2,185)', '550,333\n(+773)', '547,035\n(+50)', '534,104\n(+1,955)', '525,999\n(+4,817)', '514,592\n(+983)', '508,655\n(+797)', '499,202\n(+307)', '495,397\n(+2,536)', '481,401', '466,357\n(+179)', '459,855\n(+27)', '459,436\n(+1,282)', '411,533\n(+49)', '409,621\n(+1,012)', '401,169\n(+1,061)', '398,946', '388,572\n(+70)', '385,721\n(+1,044)', '364,758\n(+1,458)', '364,605\n(+1,588)', '357,827\n(+457)', '357,517\n(+368)', '342,305\n(+591)', '337,890', '327,896\n(+1,242)', '305,840\n(+2,289)', '303,705\n(+32)', '302,327\n(+702)', '298,919\n(+2,153)', '290,994\n(+1,039)', '290,043\n(+1,018)', '274,877\n(+63)', '259,779\n(+772)', '248,515', '236,482\n(+94)', '233,121\n(+884)', '208,912\n(+55)', '204,752\n(+296)', '202,877\n(+155)', '189,999', '187,941\n(+724)', '178,375\n(+58)', '178,050\n(+1,623)', '172,899\n(+406)', '168,188\n(+295)', '155,880\n(+804)', '155,128\n(+35)', '154,722\n(+796)', '150,540\n(+10)', '140,087\n(+409)', '130,500\n(+852)', '129,919\n(+294)', '127,373\n(+112)', '127,016\n(+395)', '123,245', '118,181\n(+136)', '110,792\n(+866)', '107,507', '104,348\n(+2,324)', '100,919\n(+1,886)', '96,982\n(+143)', '96,081\n(+31)', '89,539\n(+1,647)', '85,414', '84,484\n(+122)', '83,030\n(+252)', '77,930\n(+168)', '73,757\n(+10)', '61,517\n(+8)', '59,977\n(+98)', '56,862\n(+245)', '55,583\n(+462)', '53,241', '53,140', '50,872\n(+117)', '50,055\n(+106)', '45,812\n(+42)', '42,898', '40,545', '40,476\n(+568)', '40,178', '39,790', '38,217\n(+16)', '37,472\n(+24)', '37,119\n(+16)', '35,889\n(+30)', '33,323\n(+350)', '31,236\n(+88)', '30,364\n(+2)', '29,515\n(+389)', '25,252\n(+34)', '22,958', '22,441', '21,647\n(+107)', '21,347\n(+90)', '20,775\n(+172)', '20,242\n(+23)', '19,980\n(+257)', '19,945\n(+345)', '19,523', '19,445\n(+47)', '17,505\n(+1,149)', '17,084', '16,383\n(+10)', '16,205\n(+7)', '15,432\n(+16)', '15,391\n(+230)', '15,189\n(+22)', '15,165\n(+2)', '14,395', '14,244\n(+131)', '14,199\n(+27)', '13,730', '12,253', '12,209\n(+13)', '11,954\n(+6)', '11,806', '11,760\n(+128)', '11,371', '11,231\n(+87)', '9,930', '8,988', '7,764\n(+188)', '7,455\n(+28)', '6,838\n(+653)', '6,813\n(+113)', '6,694', '6,393', '6,099', '5,990\n(+10)', '5,794\n(+12)', '5,532\n(+15)', '5,428', '5,145\n(+163)', '5,034\n(+2)', '5,005\n(+83)', '4,235\n(+22)', '4,204\n(+10)', '4,128', '3,727', '3,445', '3,359\n(+21)', '3,349\n(+5)', '3,306\n(+3)', '3,293', '2,923', '2,834', '2,642', '2,600\n(+1)', '2,045\n(+26)', '1,872\n(+37)', '1,565', '1,367', '1,140\n(+13)', '812\n(+17)', '565', '445', '389\n(+25)', '70\n(+3)', '67', '33', '31', '27', '20', '10', '9', '5', '4', '4', '3', '2', '1']

222
['21,819\n(-275)', '8,944', '8,318', '878\n(-38)', '2,300', '633', '1,609', '6,124\n(-85)', '1,200\n(-37)', '542', '837', '488\n(+5)', '1,435', 'N/A', '4,798', '168\n(+15)', '546', '3,170', '177', '978\n(-72)', '1,025\n(+2)', '160\n(-17)', '516\n(-5)', '1,066\n(-44)', '36\n(+6)', '389\n(+9)', '638', '3,324', '1,408\n(-5)', '641', '4,015\n(-18)', '206\n(-10)', '1,267\n(+49)', '35\n(-7)', '74\n(-5)', '552\n(-46)', '251\n(+26)', '221', '406\n(+20)', '209', '74\n(+3)', '446\n(-30)', 'N/A', 'N/A', '240\n(+6)', 'N/A', '316', '323\n(-14)', '200', 'N/A', '5', '227\n(-17)', 'N/A', '443\n(-16)', 'N/A', '759', '220', '432\n(-108)', 'N/A', '61', '23', 'N/A', '10\n(-2)', '119\n(+20)', '102\n(+5)', '74', '13\n(-1)', '66\n(+1)', '681', '418\n(-33)', '15\n(-3)', '171\n(+1)', '791\n(-7)', 'N/A', '203\n(+11)', '324\n(+5)', '20\n(-2)', '90', '192', '74\n(+6)', '160\n(-1)', '4\n(+1)', 'N/A', '92', '16', 'N/A', '25\n(-3)', '11', '18', 'N/A', '21\n(+2)', '131', '1', '23', '3', '61\n(+9)', '1,124', '19\n(+2)', '32', '25', 'N/A', '12', '16\n(-1)', '42', '327', '33\n(-6)', 'N/A', 'N/A', '127', '301', '9\n(-2)', 'N/A', '27\n(-3)', '152', '23', '46\n(+15)', '8', '9\n(-1)', '67', 'N/A', 'N/A', '8', '33', '23', '10\n(-29)', '22', '10', '3', '1', '19', '24\n(-6)', '34', 'N/A', '23', '3\n(-1)', '22', 'N/A', '30\n(-3)', '24', '26\n(+3)', 'N/A', '5', 'N/A', 'N/A', 'N/A', '15', 'N/A', 'N/A', '10', '7', 'N/A', 'N/A', 'N/A', '4', 'N/A', '7', 'N/A', '4', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '4', '1', '3', '2', '15', '3', '23', 'N/A', '1', '53\n(-3)', '34\n(-4)', 'N/A', 'N/A', '4', 'N/A', '2', '2', '2', '1', 'N/A', 'N/A', '10', '5', 'N/A', '7', '2', '2', 'N/A', '2\n(-4)', 'N/A', '9', '1', '7', 'N/A', 'N/A', '1', 'N/A', '7', 'N/A', 'N/A', '2', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']

222
['709,119\n(+2,781)', '447,699\n(+337)', '594,702\n(+218)', '136,208\n(+40)', '205,531\n(+852)', '63,372\n(+206)', '116,537\n(+74)', '119,888\n(+239)', '114,954\n(+92)', '126,178\n(+33)', '86,298\n(+69)', '130,742\n(+45)', '94,049\n(+66)', '141,709\n(+124)', '275,676\n(+230)', '75,601\n(+29)', '87,216\n(+164)', '37,686\n(+281)', '55,863\n(+143)', '25,695\n(+258)', '199,314\n(+22)', '18,162\n(+8)', '22,187\n(+45)', '17,577\n(+50)', '30,454', '37,449\n(+4)', '27,698\n(+49)', '16,498\n(+129)', '27,470\n(+31)', '7,684', '27,638\n(+41)', '25,568\n(+14)', '36,658\n(+208)', '14,808\n(+27)', '17,962\n(+7)', '14,199\n(+32)', '8,142\n(+45)', '11,100\n(+35)', '7,330\n(+51)', '11,079\n(+26)', '30,179\n(+8)', '10,697\n(+17)', '11,115\n(+12)', '18,936\n(+178)', '10,986\n(+10)', '2,094', '24,794\n(+6)', '14,727\n(+48)', '8,296\n(+10)', '8,884\n(+40)', '13,394\n(+19)', '8,709\n(+5)', '4,114\n(+12)', '6,277\n(+88)', '12,731\n(+51)', '32,747\n(+27)', '18,707\n(+7)', '20,638\n(+149)', '6,476', '7,216\n(+8)', '16,191\n(+48)', '17,583\n(+56)', '2,447\n(+1)', '12,606\n(+10)', '8,614\n(+8)', '4,046', '6,053\n(+1)', '5,209', '4,427\n(+15)', '9,705\n(+26)', '2,652\n(+6)', '4,041\n(+2)', '5,439\n(+38)', '4,617', '4,946\n(+16)', '2,464\n(+8)', '4,095', '17,224\n(+37)', '1,242\n(+17)', '4,553\n(+10)', '6,713\n(+18)', '1,389', '5,277\n(+13)', '5,109', '605', '10,542\n(+34)', '3,647\n(+1)', '2,690\n(+13)', '5,786\n(+9)', '6,607', '851\n(+1)', '2,604\n(+2)', '2,367\n(+7)', '1,230\n(+5)', '2,653\n(+13)', '2,700\n(+11)', '7,204\n(+3)', '1,351\n(+5)', '1,910\n(+1)', '1,062', '1,914\n(+19)', '4,607\n(+3)', '3,494', '1,150\n(+4)', '3,146', '553', '2,287\n(+26)', '2,269', '3,211\n(+14)', '1,256\n(+12)', '1,258\n(+6)', '4,636', '80\n(+2)', '1,368', '231', '1,841\n(+7)', '835', '1,855', '2,278\n(+2)', '607\n(+7)', '1,084\n(+1)', '1,513\n(+12)', '363', '690', '621\n(+31)', '1,464\n(+7)', '1,213\n(+1)', '958', '582', '861\n(+16)', '616\n(+5)', '256', '2,900\n(+6)', '336\n(+2)', '457', '772\n(+4)', '2,215\n(+8)', '772\n(+10)', '378\n(+1)', '183\n(+5)', '227\n(+1)', '154', '16', '610', '115', '523\n(+1)', '178', '1,111\n(+8)', '405\n(+3)', '227', '114\n(+1)', '38', '124', '161\n(+1)', '842', '166\n(+1)', '79\n(+8)', '130', '547', '403', '193\n(+2)', '181\n(+1)', '203', '162', '213', '128', '142', '33', '100', '186\n(+1)', '335', '1,703', '68\n(+1)', '51', '101\n(+18)', '39\n(+1)', '42', '121', '135', '201', '283', '97', '91', '62\n(+10)', '174', '130\n(+10)', '66\n(+3)', '27', '147', '55', '60', '18\n(+1)', '49', '33', '15', '64', '23', '37', '3', '19', '11\n(+1)', '3', '50', '2', '2', '0', '7', '1', '0', '0', '1', '0', '0', '0', '1', '2', '0', '0', '1', '0', '0', '0']

222
['33,394,833\n(+208,564)', '32,976,760\n(+28,144)', '20,361,191\n(+20,818)', '6,219,111\n(+33,541)', '6,635,485\n(+17,368)', '6,522,435\n(+25,160)', '6,737,491\n(+14,460)', '4,988,109\n(+22,011)', '5,113,603\n(+2,007)', '4,793,387\n(+1,672)', '4,736,022\n(+27,855)', '4,430,265\n(+2,892)', '3,978,200\n(+11,500)', '4,031,099\n(+3,551)', '2,991,723\n(+7,262)', '2,662,115\n(+107)', '2,762,812\n(+2,719)', '2,353,140\n(+61,134)', '2,248,071\n(+2,927)', '2,005,939\n(+16,430)', 'N/A', 'N/A', '1,904,022\n(+3,795)', '1,643,625\n(+4,341)', '1,653,600\n(+431)', '1,608,584\n(+1,088)', '1,538,280\n(+10,029)', '1,448,206\n(+12,805)', '1,513,876\n(+1,195)', '1,205,657', '1,164,219\n(+2,042)', '1,152,355\n(+7,685)', '1,104,496\n(+5,701)', 'N/A', '1,019,266\n(+1,331)', '901,220\n(+2,248)', '792,262\n(+5,785)', '815,664\n(+2,781)', '826,727\n(+7,105)', '759,741', '783,815\n(+648)', '797,773\n(+1,069)', '763,734\n(+1,318)', '559,941\n(+21,487)', '707,860\n(+2,758)', '727,845\n(+329)', '673,438\n(+394)', '608,082\n(+2,382)', '591,002\n(+2,425)', '580,891\n(+2,010)', '507,777\n(+2,564)', '536,079\n(+53)', '516,030\n(+1,469)', '425,077\n(+4,873)', '455,344\n(+812)', '443,880', '458,227\n(+711)', '432,315\n(+2,268)', '452,968', '455,577\n(+180)', '442,854\n(+109)', '413,821\n(+1,866)', '408,424\n(+42)', '386,612\n(+464)', '385,455\n(+1,098)', '367,181', '381,190\n(+152)', '339,559\n(+1,926)', '347,693\n(+1,090)', '109,496\n(+557)', '350,430\n(+403)', '348,606\n(+259)', '308,938\n(+543)', '256,121', '299,479\n(+212)', '270,928\n(+1,796)', '297,252\n(+335)', '255,059\n(+588)', '284,712', '273,303\n(+1,385)', '273,920\n(+661)', '272,738\n(+61)', '240,730\n(+425)', '240,672', '234,545\n(+120)', '192,218', '204,847\n(+102)', '192,951\n(+331)', '138,961\n(+109)', '171,375', '88,952', '173,005\n(+93)', '173,004\n(+953)', '167,700\n(+501)', '154,694\n(+1,075)', '144,715', '124,362\n(+349)', '142,671\n(+186)', '146,588\n(+34)', '46,000', '121,363\n(+1,218)', '122,446\n(+197)', '122,753\n(+19)', '122,456\n(+578)', '96,059', '90,755', '101,690\n(+505)', '105,323', '86,851\n(+1,870)', '74,781', '45,465\n(+1)', '90,463\n(+61)', '75,176\n(+524)', '80,433', '82,676\n(+109)', '52,292\n(+195)', '76,026\n(+261)', '71,694\n(+82)', '54,668\n(+75)', '57,606\n(+127)', '30,858', '47,328\n(+55)', '52,010', '2,250', '36,724\n(+17)', '44,378\n(+202)', '43,983\n(+92)', '41,322', '104', '26,881\n(+17)', '33,500', '9,995', '32,044\n(+6)', '36,490\n(+42)', '35,896\n(+37)', '34,399\n(+108)', '23,599\n(+71)', '26,557\n(+287)', '28,752\n(+19)', '26,641\n(+100)', '22,433\n(+112)', '17,294', '5,568', '19,463\n(+115)', '20,903\n(+246)', '18,321\n(+56)', '2,964', '9,523\n(+109)', '17,568\n(+321)', '18,353', '18,493\n(+128)', '773', '16,960', '15,797\n(+31)', '13,742', '15,013\n(+18)', '1,854', '14,981\n(+15)', '14,271\n(+7)', '6,830', '12,421', '13,856\n(+44)', '4,225', '11,838', '11,897\n(+5)', '11,570\n(+148)', '10,225', '11,372\n(+121)', '6,859', '8,874\n(+72)', '9,571', '5,570', '6,634\n(+162)', '7,096\n(+31)', '58', '4,582\n(+139)', '6,628', '4,380', '5,283', '5,746\n(+11)', '5,458', '5,373\n(+8)', '5,310', '3,613\n(+295)', '4,853\n(+3)', '3,080\n(+221)', '4,012\n(+28)', '3,961\n(+16)', '3,960', '1,399', '3,355', '2,388\n(+7)', '2,680\n(+5)', '3,245\n(+3)', '2,680', '1,882', '2,749\n(+1)', '2,555', '2,593', '1,918', '976\n(+6)', '462', '183', '1,059\n(+8)', '761\n(+14)', '398', '438', '362\n(+17)', '63', '63', '30', '31', '27', '20', '8', '7', '5', '4', '3', '3', '2', '1']

222
['1.6', '1.3', '2.8', '1.8', '2.8', '0.9', '1.7', '2.2', '2.2', '2.5', '1.7', '2.8', '2.2', '3.4', '7.6', '2.6', '3.0', '1.5', '2.3', '1.2', '9.2', '0.9', '1.1', '1.0', '1.8', '2.3', '1.7', '1.0', '1.8', '0.6', '2.2', '2.1', '3.0', '1.3', '1.7', '1.5', '0.9', '1.3', '0.8', '1.3', '3.7', '1.3', '1.4', '2.5', '1.5', '0.3', '3.5', '2.3', '1.3', '1.5', '2.4', '1.6', '0.8', '1.2', '2.5', '6.4', '3.7', '4.2', '1.3', '1.5', '3.5', '3.8', '0.6', '3.1', '2.1', '1.0', '1.6', '1.4', '1.2', '2.7', '0.7', '1.1', '1.6', '1.4', '1.5', '0.8', '1.3', '5.7', '0.4', '1.6', '2.3', '0.5', '2.0', '2.1', '0.3', '4.5', '1.7', '1.3', '2.9', '3.5', '0.5', '1.5', '1.3', '0.7', '1.6', '1.7', '4.6', '0.9', '1.3', '0.8', '1.5', '3.5', '2.7', '0.9', '2.6', '0.5', '2.1', '2.1', '3.1', '1.2', '1.3', '4.8', '0.1', '1.6', '0.3', '2.2', '1.1', '2.5', '3.7', '1.0', '1.9', '2.7', '0.7', '1.3', '1.2', '2.9', '2.6', '2.2', '1.4', '2.1', '1.5', '0.6', '7.6', '0.9', '1.2', '2.2', '6.6', '2.5', '1.2', '0.6', '0.9', '0.7', '0.1', '2.8', '0.5', '2.5', '0.9', '5.6', '2.0', '1.2', '0.6', '0.2', '0.7', '1.0', '5.2', '1.1', '0.5', '0.9', '3.6', '2.8', '1.4', '1.3', '1.5', '1.3', '1.7', '1.1', '1.2', '0.3', '0.9', '1.7', '3.4', '18.9', '0.9', '0.7', '1.5', '0.6', '0.6', '1.9', '2.2', '3.4', '4.9', '1.8', '1.7', '1.2', '3.5', '2.6', '1.6', '0.6', '3.6', '1.5', '1.7', '0.5', '1.5', '1.0', '0.5', '2.2', '0.8', '1.4', '0.1', '0.9', '0.6', '0.2', '3.7', '0.2', '0.2', '-', '1.6', '0.3', '-', '-', '3.0', '-', '-', '-', '10', '22.2', '-', '-', '25', '-', '-', '-']

222
['76.0', '97.8', '95.3', '80.7', '88.9', '92.3', '96.3', '89.7', '97.4', '96.8', '95.6', '95.0', '94.4', '95.7', '82.3', '91.7', '95.4', '93.3', '93.6', '90.8', 'N/A', 'N/A', '95.3', '96.8', '97.8', '97.3', '95.4', '91.6', '97.4', '94.9', '93.8', '93.1', '91.2', 'N/A', '95.5', '96.9', '85.5', '92.6', '95.4', '90.7', '95.4', '97.2', '96.3', '72.7', '95.8', '99.0', '95.5', '93.8', '94.9', '95.3', '92.3', '98.0', '96.6', '80.8', '88.5', '87.3', '91.8', '87.3', '94.1', '97.7', '96.3', '90.1', '99.2', '94.4', '96.1', '92.0', '98.1', '88.0', '95.3', '30.0', '97.9', '97.5', '90.3', '75.8', '91.3', '88.6', '97.9', '84.4', '95.2', '93.9', '94.4', '99.2', '92.7', '96.8', '99.2', '82.5', '98.1', '94.2', '68.5', '90.2', '47.3', '97.0', '97.2', '97.0', '92.0', '92.8', '80.2', '92.2', '97.4', '32.8', '93.0', '94.2', '96.4', '96.4', '77.9', '76.8', '91.8', '98.0', '83.2', '74.1', '46.9', '94.2', '84.0', '94.2', '97.9', '63.0', '97.6', '97.2', '88.9', '96.0', '54.3', '85.1', '97.7', '4.2', '72.2', '88.7', '96.0', '96.3', '0.3', '66.4', '83.4', '25.1', '83.8', '97.4', '96.7', '95.8', '70.8', '85.0', '94.7', '90.3', '88.8', '75.3', '24.8', '89.9', '97.9', '88.2', '14.6', '47.7', '88.1', '94.0', '95.1', '4.4', '99.3', '96.4', '84.8', '97.3', '12.0', '98.6', '94.1', '47.4', '87.2', '97.6', '30.8', '96.6', '97.4', '96.8', '86.6', '96.7', '60.3', '79.0', '96.4', '62.0', '85.4', '95.2', '0.8', '67.3', '99.0', '68.5', '86.6', '95.9', '94.2', '97.1', '97.8', '70.2', '96.4', '61.5', '94.7', '94.2', '95.9', '37.5', '97.4', '71.1', '80.0', '98.2', '81.4', '64.4', '97.0', '96.7', '99.7', '93.8', '52.1', '29.5', '13.4', '92.9', '93.7', '70.4', '98.4', '93.1', '90', '94.0', '90.9', '100', '100', '100', '80', '77.8', '100', '100', '75', '100', '100', '100']

222
['133,095', '24,431', '100,592', '113,959', '51,151', '84,132', '107,278', '66,192', '116,245', '97,368', '105,956', '77,157', '50,350', '15,397', '28,275', '76,747', '48,878', '23,024', '54,922', '68,607', '65,942', '116,697', '49,689', '13,428', '157,838', '86,460', '42,813', '22,806', '9,435', '147,235', '5,629', '107,012', '62,939', '113,986', '104,718', '25,220', '106,012', '47,007', '76,528', '96,800', '85,041', '80,548', '27,226', '7,917', '82,026', '74,361', '59,692', '62,494', '91,274', '152,749', '30,883', '15,713', '56,523', '103,664', '24,075', '28,830', '42,804', '71,666', '47,479', '108,138', '64,479', '8,474', '96,374', '75,027', '97,721', '78,537', '111,897', '78,419', '12,876', '36,878', '61,777', '33,000', '2,984', '49,274', '120,449', '6,022', '59,473', '2,961', '91,949', '139,972', '72,200', '161,571', '87,667', '4,626', '82,082', '71,056', '11,364', '995', '4,630', '91,420', '34,733', '27,341', '75,714', '5,166', '58,650', '82,642', '3,985', '116,636', '4,817', '25,283', '207,781', '8,765', '50,176', '4,088', '2,696', '97,981', '6,627', '59,381', '16,088', '4,029', '7,504', '67', '15,687', '3,218', '156,470', '28,145', '124,602', '4,405', '3,216', '2,275', '635', '1,705', '59,959', '132,809', '56,749', '35,891', '39,538', '1,549', '108,044', '69,872', '143,029', '135,827', '872', '67,449', '84,067', '7,730', '1,922', '39,869', '2,313', '13,261', '3,059', '1,894', '3,153', '1,898', '217,058', '53,000', '74,197', '1,257', '51,040', '2,182', '14,748', '1,472', '1,791', '100,114', '680', '144,690', '12,102', '196,622', '750', '6,720', '2,581', '679', '2,181', '12,789', '1,629', '1,070', '8,415', '34,462', '2,354', '61,647', '4,109', '302', '27,772', '88,319', '23,951', '15,573', '1,888', '801', '3,101', '248', '1,146', '164,198', '159,972', '82,613', '307', '44,782', '99,426', '881', '4,757', '96,390', '90,354', '30,368', '15,550', '84,399', '45,745', '32,268', '73,249', '87,394', '3,370', '78,862', '35,546', '158,449', '23', '23,331', '12,477', '10,058', '-', '25,928', '109', '19,253', '6,611', '5,350', '33,708', '29', '17', '-', '276', '68', '13', '15', '329', '9']

222
['331,002,651', '1,380,004,385', '212,559,417', '67,886,011', '145,934,462', '84,339,067', '65,273,511', '83,992,949', '45,195,774', '50,882,891', '46,754,778', '60,461,826', '83,783,942', '273,523,615', '128,932,753', '37,846,611', '59,308,690', '109,581,078', '43,733,762', '32,365,999', '32,971,854', '17,134,872', '40,222,493', '126,476,461', '10,708,981', '19,116,201', '37,742,154', '69,799,978', '164,689,383', '8,655,535', '220,892,340', '11,589,623', '19,237,691', '10,099,265', '10,196,709', '36,910,560', '8,737,371', '18,776,707', '11,326,616', '8,654,622', '9,660,351', '10,203,134', '29,136,808', '97,338,579', '9,006,398', '9,890,402', '11,818,619', '10,423,054', '6,825,445', '3,989,167', '17,915,568', '34,813,871', '9,449,323', '5,094,118', '21,413,249', '17,643,054', '11,673,021', '6,948,445', '10,139,177', '4,314,767', '7,132,538', '54,409,800', '4,270,571', '5,459,642', '4,105,267', '5,101,414', '3,473,730', '4,937,786', '28,435,940', '9,904,607', '5,792,202', '10,847,910', '114,963,588', '6,871,292', '2,722,289', '51,269,185', '5,106,626', '102,334,404', '3,278,290', '2,078,938', '4,033,963', '1,701,575', '2,963,243', '53,771,296', '2,881,053', '3,280,819', '18,383,955', '206,139,589', '43,851,044', '2,083,374', '5,421,241', '6,524,195', '2,351,627', '33,469,203', '2,877,797', '1,886,198', '38,928,346', '1,326,535', '31,255,435', '5,540,720', '628,066', '14,862,924', '2,540,905', '31,072,940', '45,741,007', '1,207,359', '16,718,965', '1,810,463', '6,486,205', '25,499,884', '12,952,218', '1,439,323,776', '5,850,342', '26,545,863', '540,544', '2,961,167', '625,978', '16,743,927', '19,129,952', '26,378,274', '89,561,403', '32,866,272', '895,312', '400,124', '896,445', '1,399,488', '1,160,164', '27,691,018', '375,265', '586,632', '280,908', '298,682', '43,849,260', '555,987', '441,543', '4,649,658', '17,500,658', '786,552', '13,132,795', '2,225,734', '8,278,724', '12,123,200', '7,275,560', '11,402,528', '98,347', '393,244', '272,815', '15,893,222', '397,628', '8,947,024', '1,318,445', '11,890,784', '9,537,645', '164,093', '23,816,775', '106,766', '1,271,768', '77,265', '20,250,833', '2,142,249', '5,518,087', '20,903,273', '6,624,554', '988,000', '7,496,981', '11,193,725', '1,402,985', '341,243', '4,829,767', '183,627', '2,416,668', '29,825,964', '287,375', '85,033', '285,498', '437,479', '3,546,421', '7,976,983', '1,968,001', '24,206,644', '5,057,681', '33,691', '33,931', '62,278', '16,425,864', '112,523', '42,876', '4,822,233', '869,601', '38,666', '38,128', '110,940', '219,159', '39,242', '71,986', '97,929', '38,717', '30,231', '771,608', '26,223', '53,199', '9,877', '59,734,218', '48,863', '65,722', '56,770', '-', '15,003', '649,335', '3,480', '4,992', '5,794', '801', '686,884', '597,339', '-', '18,094', '59,190', '307,145', '198,414', '6,077', '115,023']

[['미국🇺🇸',
  '인도🇮🇳',
  '브라질🇧🇷',
  '영국🇬🇧',
  '러시아🇷🇺',
  '터키🇹🇷',
  '프랑스🇫🇷',
  '이란🇮🇷',
  '아르헨티나🇦🇷',
  '콜롬비아🇨🇴',
  '스페인🇪🇸',
  '이탈리아🇮🇹',
  '독일🇩🇪',
  '인도네시아🇮🇩',
  '멕시코🇲🇽',
  '폴란드🇵🇱',
  '남아프리카 공화국🇿🇦',
  '필리핀🇵🇭',
  '우크라이나🇺🇦',
  '말레이시아🇲🇾',
  '페루🇵🇪',
  '네덜란드🇳🇱',
  '이라크🇮🇶',
  '일본🇯🇵*',
  '체코🇨🇿',
  '칠레🇨🇱',
  '캐나다🇨🇦',
  '태국🇹🇭',
  '방글라데시🇧🇩',
  '이스라엘🇮🇱',
  '파키스탄🇵🇰',
  '벨기에🇧🇪',
  '루마니아🇷🇴',
  '스웨덴🇸🇪',
  '포르투갈🇵🇹',
  '모로코🇲🇦',
  '세르비아🇷🇸',
  '카자흐스탄🇰🇿',
  '쿠바🇨🇺',
  '스위스🇨🇭',
  '헝가리🇭🇺',
  '요르단🇯🇴',
  '네팔🇳🇵',
  '베트남🇻🇳',
  '오스트리아🇦🇹',
  '아랍에미레이트🇦🇪',
  '튀니지🇹🇳',
  '그리스🇬🇷',
  '레바논🇱🇧',
  '조지아🇬🇪',
  '과테말라🇬🇹',
  '사우디아라비아🇸🇦',
  '벨라루스🇧🇾',
  '코스타리카🇨🇷',
  '스리랑카🇱🇰',
  '에콰도르🇪🇨',
  '볼리비아🇧🇴',
  '불가리아🇧🇬',
  '아제르바이잔🇦🇿',
  '파나마🇵🇦',
  '파라과이🇵🇾',
  '미얀마🇲🇲',
  '쿠웨이트🇰🇼',
  '슬로바키아🇸🇰',
  '크로아티아🇭🇷',
  '팔레스타인🇵🇸',
  '우루과이🇺🇾',
  '아일랜드🇮🇪',
  '베네수엘라🇻🇪',
  '온두라스🇭🇳',
  '덴마크🇩🇰',
  '도미니카 공화국🇩🇴',
  '에티오피아🇪🇹',
  '리비아🇱🇾',
  '리투아니아🇱🇹',
  '대한민국🇰🇷',
  '오만🇴🇲',
  '이집트🇪🇬',
  '몽골🇲🇳',
  '슬로베니아🇸🇮',
  '몰도바🇲🇩',
  '바레인🇧🇭',
  '아르메니아🇦🇲',
  '케냐🇰🇪',
  '카타르🇶🇦',
  '보스니아 헤르체고비나🇧🇦',
  '잠비아🇿🇲',
  '나이지리아🇳🇬',
  '알제리🇩🇿',
  '북마케도니아🇲🇰',
  '노르웨이🇳🇴',
  '키르기스스탄🇰🇬',
  '보츠와나🇧🇼',
  '우즈베키스탄🇺🇿',
  '알바니아🇦🇱',
  '라트비아🇱🇻',
  '아프가니스탄🇦🇫',
  '에스토니아🇪🇪',
  '모잠비크🇲🇿',
  '핀란드🇫🇮',
  '몬테네그로🇲🇪',
  '짐바브웨🇿🇼',
  '나미비아🇳🇦',
  '가나🇬🇭',
  '우간다🇺🇬',
  '키프로스🇨🇾',
  '캄보디아🇰🇭',
  '코소보🇽🇰',
  '엘살바도르🇸🇻',
  '호주🇦🇺',
  '르완다🇷🇼',
  '중국🇨🇳',
  '싱가포르🇸🇬',
  '카메룬🇨🇲',
  '몰디브🇲🇻',
  '자메이카🇯🇲',
  '룩셈부르크🇱🇺',
  '세네갈🇸🇳',
  '말라위🇲🇼',
  '코트디부아르🇨🇮',
  '콩고민주공화국🇨🇩',
  '앙골라🇦🇴',
  '레위니옹🇷🇪',
  '과들루프🇬🇵',
  '피지🇫🇯',
  '트리니다드 토바고🇹🇹',
  '에스와티니🇸🇿',
  '마다가스카르🇲🇬',
  '마르티니크🇲🇶',
  '수리남🇸🇷',
  '프랑스령 폴리네시아🇵🇫',
  '프랑스령 기아나🇬🇫',
  '수단🇸🇩',
  '카보베르데🇨🇻',
  '몰타 공화국🇲🇹',
  '모리타니🇲🇷',
  '시리아🇸🇾',
  '가이아나🇬🇾',
  '기니🇬🇳',
  '가봉🇬🇦',
  '토고🇹🇬',
  '베냉🇧🇯',
  '라오스🇱🇦',
  '아이티🇭🇹',
  '세이셸🇸🇨',
  '바하마🇧🇸',
  '마요트🇾🇹',
  '소말리아🇸🇴',
  '벨리즈🇧🇿',
  '파푸아뉴기니🇵🇬',
  '동티모르🇹🇱',
  '부룬디🇧🇮',
  '타지키스탄🇹🇯',
  '퀴라소🇨🇼',
  '대만🇹🇼',
  '아루바🇦🇼',
  '모리셔스🇲🇺',
  '안도라🇦🇩',
  '말리🇲🇱',
  '레소토🇱🇸',
  '콩고공화국🇨🇬',
  '부르키나파소🇧🇫',
  '니카라과🇳🇮',
  '지부티🇩🇯',
  '홍콩🇭🇰',
  '남수단🇸🇸',
  '적도 기니🇬🇶',
  '아이슬란드🇮🇸',
  '중앙아프리카 공화국🇨🇫',
  '세인트루시아🇱🇨',
  '감비아🇬🇲',
  '예멘🇾🇪',
  '바베이도스🇧🇧',
  '맨섬🇮🇲',
  '뉴칼레도니아🇳🇨',
  '브루나이🇧🇳',
  '에리트레아🇪🇷',
  '시에라리온🇸🇱',
  '기니비사우🇬🇼',
  '니제르🇳🇪',
  '라이베리아🇱🇷',
  '지브롤터🇬🇮',
  '산마리노🇸🇲',
  '버뮤다🇧🇲',
  '차드🇹🇩',
  '그레나다🇬🇩',
  '신트마르턴🇸🇽',
  '뉴질랜드🇳🇿',
  '코모로🇰🇲',
  '세인트마틴 섬🇲🇫',
  '리히텐슈타인🇱🇮',
  '세인트빈센트 그레나딘🇻🇨',
  '상투메 프린시페🇸🇹',
  '모나코🇲🇨',
  '도미니카 연방🇩🇲',
  '앤티가 바부다🇦🇬',
  '터크스 케이커스 제도🇹🇨',
  '영국령 버진아일랜드🇻🇬',
  '부탄🇧🇹',
  '카리브 네덜란드🇧🇶',
  '세인트키츠 네비스🇰🇳',
  '생바르텔레미🇧🇱',
  '탄자니아🇹🇿',
  '페로 제도🇫🇴',
  '케이맨 제도🇰🇾',
  '그린란드🇬🇱',
  '왈리스 퓌티나🇼🇫',
  '앵귈라🇦🇮',
  '마카오🇲🇴',
  '포클랜드 제도🇫🇰',
  '몬트세랫🇲🇸',
  '생피에르 미클롱🇵🇲',
  '바티칸 시국🇻🇦',
  '솔로몬 제도🇸🇧',
  '서사하라🇪🇭',
  '잔담(크루즈)🚢',
  '팔라우🇵🇼',
  '마셜 제도🇲🇭',
  '바누아투🇻🇺',
  '사모아🇼🇸',
  '세인트헬레나🇸🇭',
  '미크로네시아🇫🇲'],
 ['43,942,335\n(+187,382)',
  '33,714,241\n(+21,093)',
  '21,366,395\n(+14,423)',
  '7,701,715\n(+37,485)',
  '7,464,708\n(+21,559)',
  '7,066,688\n(+27,188)',
  '6,995,628\n(+1,309)',
  '5,559,691\n(+11,701)',
  '5,251,940\n(+1,538)',
  '4,952,690\n(+1,015)',
  '4,951,640\n(+5,039)',
  '4,662,087\n(+1,773)',
  '4,212,201\n(+4,941)',
  '4,211,460\n(+2,057)',
  '3,635,807\n(+3,007)',
  '2,904,631\n(+976)',
  '2,897,521\n(+578)',
  '2,522,965\n(+32,107)',
  '2,401,956\n(+6,552)',
  '2,209,194\n(+10,959)',
  '2,173,354\n(+320)',
  '1,999,592\n(+1,707)',
  '1,998,615\n(+2,401)',
  '1,698,344\n(+1,722)',
  '1,690,288\n(+668)',
  '1,652,795\n(+431)',
  '1,612,431\n(+10,052)',
  '1,581,415\n(+9,489)',
  '1,553,873\n(+1,310)',
  '1,270,230',
  '1,241,825\n(+1,400)',
  '1,238,358\n(+4,635)',
  '1,210,810\n(+11,049)',
  '1,151,173\n(+1,766)',
  '1,067,775\n(+600)',
  '929,699\n(+394)',
  '926,269\n(+8,467)',
  '880,709\n(+1,719)',
  '866,808\n(+6,009)',
  '837,767\n(+1,288)',
  '821,526\n(+265)',
  '820,798\n(+1,015)',
  '793,271\n(+904)',
  '770,640\n(+4,589)',
  '738,763\n(+1,561)',
  '735,457\n(+277)',
  '705,474\n(+179)',
  '648,091\n(+2,122)',
  '622,440\n(+205)',
  '609,340\n(+2,185)',
  '550,333\n(+773)',
  '547,035\n(+50)',
  '534,104\n(+1,955)',
  '525,999\n(+4,817)',
  '514,592\n(+983)',
  '508,655\n(+797)',
  '499,202\n(+307)',
  '495,397\n(+2,536)',
  '481,401',
  '466,357\n(+179)',
  '459,855\n(+27)',
  '459,436\n(+1,282)',
  '411,533\n(+49)',
  '409,621\n(+1,012)',
  '401,169\n(+1,061)',
  '398,946',
  '388,572\n(+70)',
  '385,721\n(+1,044)',
  '364,758\n(+1,458)',
  '364,605\n(+1,588)',
  '357,827\n(+457)',
  '357,517\n(+368)',
  '342,305\n(+591)',
  '337,890',
  '327,896\n(+1,242)',
  '305,840\n(+2,289)',
  '303,705\n(+32)',
  '302,327\n(+702)',
  '298,919\n(+2,153)',
  '290,994\n(+1,039)',
  '290,043\n(+1,018)',
  '274,877\n(+63)',
  '259,779\n(+772)',
  '248,515',
  '236,482\n(+94)',
  '233,121\n(+884)',
  '208,912\n(+55)',
  '204,752\n(+296)',
  '202,877\n(+155)',
  '189,999',
  '187,941\n(+724)',
  '178,375\n(+58)',
  '178,050\n(+1,623)',
  '172,899\n(+406)',
  '168,188\n(+295)',
  '155,880\n(+804)',
  '155,128\n(+35)',
  '154,722\n(+796)',
  '150,540\n(+10)',
  '140,087\n(+409)',
  '130,500\n(+852)',
  '129,919\n(+294)',
  '127,373\n(+112)',
  '127,016\n(+395)',
  '123,245',
  '118,181\n(+136)',
  '110,792\n(+866)',
  '107,507',
  '104,348\n(+2,324)',
  '100,919\n(+1,886)',
  '96,982\n(+143)',
  '96,081\n(+31)',
  '89,539\n(+1,647)',
  '85,414',
  '84,484\n(+122)',
  '83,030\n(+252)',
  '77,930\n(+168)',
  '73,757\n(+10)',
  '61,517\n(+8)',
  '59,977\n(+98)',
  '56,862\n(+245)',
  '55,583\n(+462)',
  '53,241',
  '53,140',
  '50,872\n(+117)',
  '50,055\n(+106)',
  '45,812\n(+42)',
  '42,898',
  '40,545',
  '40,476\n(+568)',
  '40,178',
  '39,790',
  '38,217\n(+16)',
  '37,472\n(+24)',
  '37,119\n(+16)',
  '35,889\n(+30)',
  '33,323\n(+350)',
  '31,236\n(+88)',
  '30,364\n(+2)',
  '29,515\n(+389)',
  '25,252\n(+34)',
  '22,958',
  '22,441',
  '21,647\n(+107)',
  '21,347\n(+90)',
  '20,775\n(+172)',
  '20,242\n(+23)',
  '19,980\n(+257)',
  '19,945\n(+345)',
  '19,523',
  '19,445\n(+47)',
  '17,505\n(+1,149)',
  '17,084',
  '16,383\n(+10)',
  '16,205\n(+7)',
  '15,432\n(+16)',
  '15,391\n(+230)',
  '15,189\n(+22)',
  '15,165\n(+2)',
  '14,395',
  '14,244\n(+131)',
  '14,199\n(+27)',
  '13,730',
  '12,253',
  '12,209\n(+13)',
  '11,954\n(+6)',
  '11,806',
  '11,760\n(+128)',
  '11,371',
  '11,231\n(+87)',
  '9,930',
  '8,988',
  '7,764\n(+188)',
  '7,455\n(+28)',
  '6,838\n(+653)',
  '6,813\n(+113)',
  '6,694',
  '6,393',
  '6,099',
  '5,990\n(+10)',
  '5,794\n(+12)',
  '5,532\n(+15)',
  '5,428',
  '5,145\n(+163)',
  '5,034\n(+2)',
  '5,005\n(+83)',
  '4,235\n(+22)',
  '4,204\n(+10)',
  '4,128',
  '3,727',
  '3,445',
  '3,359\n(+21)',
  '3,349\n(+5)',
  '3,306\n(+3)',
  '3,293',
  '2,923',
  '2,834',
  '2,642',
  '2,600\n(+1)',
  '2,045\n(+26)',
  '1,872\n(+37)',
  '1,565',
  '1,367',
  '1,140\n(+13)',
  '812\n(+17)',
  '565',
  '445',
  '389\n(+25)',
  '70\n(+3)',
  '67',
  '33',
  '31',
  '27',
  '20',
  '10',
  '9',
  '5',
  '4',
  '4',
  '3',
  '2',
  '1'],
 ['21,819\n(-275)',
  '8,944',
  '8,318',
  '878\n(-38)',
  '2,300',
  '633',
  '1,609',
  '6,124\n(-85)',
  '1,200\n(-37)',
  '542',
  '837',
  '488\n(+5)',
  '1,435',
  'N/A',
  '4,798',
  '168\n(+15)',
  '546',
  '3,170',
  '177',
  '978\n(-72)',
  '1,025\n(+2)',
  '160\n(-17)',
  '516\n(-5)',
  '1,066\n(-44)',
  '36\n(+6)',
  '389\n(+9)',
  '638',
  '3,324',
  '1,408\n(-5)',
  '641',
  '4,015\n(-18)',
  '206\n(-10)',
  '1,267\n(+49)',
  '35\n(-7)',
  '74\n(-5)',
  '552\n(-46)',
  '251\n(+26)',
  '221',
  '406\n(+20)',
  '209',
  '74\n(+3)',
  '446\n(-30)',
  'N/A',
  'N/A',
  '240\n(+6)',
  'N/A',
  '316',
  '323\n(-14)',
  '200',
  'N/A',
  '5',
  '227\n(-17)',
  'N/A',
  '443\n(-16)',
  'N/A',
  '759',
  '220',
  '432\n(-108)',
  'N/A',
  '61',
  '23',
  'N/A',
  '10\n(-2)',
  '119\n(+20)',
  '102\n(+5)',
  '74',
  '13\n(-1)',
  '66\n(+1)',
  '681',
  '418\n(-33)',
  '15\n(-3)',
  '171\n(+1)',
  '791\n(-7)',
  'N/A',
  '203\n(+11)',
  '324\n(+5)',
  '20\n(-2)',
  '90',
  '192',
  '74\n(+6)',
  '160\n(-1)',
  '4\n(+1)',
  'N/A',
  '92',
  '16',
  'N/A',
  '25\n(-3)',
  '11',
  '18',
  'N/A',
  '21\n(+2)',
  '131',
  '1',
  '23',
  '3',
  '61\n(+9)',
  '1,124',
  '19\n(+2)',
  '32',
  '25',
  'N/A',
  '12',
  '16\n(-1)',
  '42',
  '327',
  '33\n(-6)',
  'N/A',
  'N/A',
  '127',
  '301',
  '9\n(-2)',
  'N/A',
  '27\n(-3)',
  '152',
  '23',
  '46\n(+15)',
  '8',
  '9\n(-1)',
  '67',
  'N/A',
  'N/A',
  '8',
  '33',
  '23',
  '10\n(-29)',
  '22',
  '10',
  '3',
  '1',
  '19',
  '24\n(-6)',
  '34',
  'N/A',
  '23',
  '3\n(-1)',
  '22',
  'N/A',
  '30\n(-3)',
  '24',
  '26\n(+3)',
  'N/A',
  '5',
  'N/A',
  'N/A',
  'N/A',
  '15',
  'N/A',
  'N/A',
  '10',
  '7',
  'N/A',
  'N/A',
  'N/A',
  '4',
  'N/A',
  '7',
  'N/A',
  '4',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '4',
  '1',
  '3',
  '2',
  '15',
  '3',
  '23',
  'N/A',
  '1',
  '53\n(-3)',
  '34\n(-4)',
  'N/A',
  'N/A',
  '4',
  'N/A',
  '2',
  '2',
  '2',
  '1',
  'N/A',
  'N/A',
  '10',
  '5',
  'N/A',
  '7',
  '2',
  '2',
  'N/A',
  '2\n(-4)',
  'N/A',
  '9',
  '1',
  '7',
  'N/A',
  'N/A',
  '1',
  'N/A',
  '7',
  'N/A',
  'N/A',
  '2',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  'N/A'],
 ['709,119\n(+2,781)',
  '447,699\n(+337)',
  '594,702\n(+218)',
  '136,208\n(+40)',
  '205,531\n(+852)',
  '63,372\n(+206)',
  '116,537\n(+74)',
  '119,888\n(+239)',
  '114,954\n(+92)',
  '126,178\n(+33)',
  '86,298\n(+69)',
  '130,742\n(+45)',
  '94,049\n(+66)',
  '141,709\n(+124)',
  '275,676\n(+230)',
  '75,601\n(+29)',
  '87,216\n(+164)',
  '37,686\n(+281)',
  '55,863\n(+143)',
  '25,695\n(+258)',
  '199,314\n(+22)',
  '18,162\n(+8)',
  '22,187\n(+45)',
  '17,577\n(+50)',
  '30,454',
  '37,449\n(+4)',
  '27,698\n(+49)',
  '16,498\n(+129)',
  '27,470\n(+31)',
  '7,684',
  '27,638\n(+41)',
  '25,568\n(+14)',
  '36,658\n(+208)',
  '14,808\n(+27)',
  '17,962\n(+7)',
  '14,199\n(+32)',
  '8,142\n(+45)',
  '11,100\n(+35)',
  '7,330\n(+51)',
  '11,079\n(+26)',
  '30,179\n(+8)',
  '10,697\n(+17)',
  '11,115\n(+12)',
  '18,936\n(+178)',
  '10,986\n(+10)',
  '2,094',
  '24,794\n(+6)',
  '14,727\n(+48)',
  '8,296\n(+10)',
  '8,884\n(+40)',
  '13,394\n(+19)',
  '8,709\n(+5)',
  '4,114\n(+12)',
  '6,277\n(+88)',
  '12,731\n(+51)',
  '32,747\n(+27)',
  '18,707\n(+7)',
  '20,638\n(+149)',
  '6,476',
  '7,216\n(+8)',
  '16,191\n(+48)',
  '17,583\n(+56)',
  '2,447\n(+1)',
  '12,606\n(+10)',
  '8,614\n(+8)',
  '4,046',
  '6,053\n(+1)',
  '5,209',
  '4,427\n(+15)',
  '9,705\n(+26)',
  '2,652\n(+6)',
  '4,041\n(+2)',
  '5,439\n(+38)',
  '4,617',
  '4,946\n(+16)',
  '2,464\n(+8)',
  '4,095',
  '17,224\n(+37)',
  '1,242\n(+17)',
  '4,553\n(+10)',
  '6,713\n(+18)',
  '1,389',
  '5,277\n(+13)',
  '5,109',
  '605',
  '10,542\n(+34)',
  '3,647\n(+1)',
  '2,690\n(+13)',
  '5,786\n(+9)',
  '6,607',
  '851\n(+1)',
  '2,604\n(+2)',
  '2,367\n(+7)',
  '1,230\n(+5)',
  '2,653\n(+13)',
  '2,700\n(+11)',
  '7,204\n(+3)',
  '1,351\n(+5)',
  '1,910\n(+1)',
  '1,062',
  '1,914\n(+19)',
  '4,607\n(+3)',
  '3,494',
  '1,150\n(+4)',
  '3,146',
  '553',
  '2,287\n(+26)',
  '2,269',
  '3,211\n(+14)',
  '1,256\n(+12)',
  '1,258\n(+6)',
  '4,636',
  '80\n(+2)',
  '1,368',
  '231',
  '1,841\n(+7)',
  '835',
  '1,855',
  '2,278\n(+2)',
  '607\n(+7)',
  '1,084\n(+1)',
  '1,513\n(+12)',
  '363',
  '690',
  '621\n(+31)',
  '1,464\n(+7)',
  '1,213\n(+1)',
  '958',
  '582',
  '861\n(+16)',
  '616\n(+5)',
  '256',
  '2,900\n(+6)',
  '336\n(+2)',
  '457',
  '772\n(+4)',
  '2,215\n(+8)',
  '772\n(+10)',
  '378\n(+1)',
  '183\n(+5)',
  '227\n(+1)',
  '154',
  '16',
  '610',
  '115',
  '523\n(+1)',
  '178',
  '1,111\n(+8)',
  '405\n(+3)',
  '227',
  '114\n(+1)',
  '38',
  '124',
  '161\n(+1)',
  '842',
  '166\n(+1)',
  '79\n(+8)',
  '130',
  '547',
  '403',
  '193\n(+2)',
  '181\n(+1)',
  '203',
  '162',
  '213',
  '128',
  '142',
  '33',
  '100',
  '186\n(+1)',
  '335',
  '1,703',
  '68\n(+1)',
  '51',
  '101\n(+18)',
  '39\n(+1)',
  '42',
  '121',
  '135',
  '201',
  '283',
  '97',
  '91',
  '62\n(+10)',
  '174',
  '130\n(+10)',
  '66\n(+3)',
  '27',
  '147',
  '55',
  '60',
  '18\n(+1)',
  '49',
  '33',
  '15',
  '64',
  '23',
  '37',
  '3',
  '19',
  '11\n(+1)',
  '3',
  '50',
  '2',
  '2',
  '0',
  '7',
  '1',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '1',
  '2',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0'],
 ['33,394,833\n(+208,564)',
  '32,976,760\n(+28,144)',
  '20,361,191\n(+20,818)',
  '6,219,111\n(+33,541)',
  '6,635,485\n(+17,368)',
  '6,522,435\n(+25,160)',
  '6,737,491\n(+14,460)',
  '4,988,109\n(+22,011)',
  '5,113,603\n(+2,007)',
  '4,793,387\n(+1,672)',
  '4,736,022\n(+27,855)',
  '4,430,265\n(+2,892)',
  '3,978,200\n(+11,500)',
  '4,031,099\n(+3,551)',
  '2,991,723\n(+7,262)',
  '2,662,115\n(+107)',
  '2,762,812\n(+2,719)',
  '2,353,140\n(+61,134)',
  '2,248,071\n(+2,927)',
  '2,005,939\n(+16,430)',
  'N/A',
  'N/A',
  '1,904,022\n(+3,795)',
  '1,643,625\n(+4,341)',
  '1,653,600\n(+431)',
  '1,608,584\n(+1,088)',
  '1,538,280\n(+10,029)',
  '1,448,206\n(+12,805)',
  '1,513,876\n(+1,195)',
  '1,205,657',
  '1,164,219\n(+2,042)',
  '1,152,355\n(+7,685)',
  '1,104,496\n(+5,701)',
  'N/A',
  '1,019,266\n(+1,331)',
  '901,220\n(+2,248)',
  '792,262\n(+5,785)',
  '815,664\n(+2,781)',
  '826,727\n(+7,105)',
  '759,741',
  '783,815\n(+648)',
  '797,773\n(+1,069)',
  '763,734\n(+1,318)',
  '559,941\n(+21,487)',
  '707,860\n(+2,758)',
  '727,845\n(+329)',
  '673,438\n(+394)',
  '608,082\n(+2,382)',
  '591,002\n(+2,425)',
  '580,891\n(+2,010)',
  '507,777\n(+2,564)',
  '536,079\n(+53)',
  '516,030\n(+1,469)',
  '425,077\n(+4,873)',
  '455,344\n(+812)',
  '443,880',
  '458,227\n(+711)',
  '432,315\n(+2,268)',
  '452,968',
  '455,577\n(+180)',
  '442,854\n(+109)',
  '413,821\n(+1,866)',
  '408,424\n(+42)',
  '386,612\n(+464)',
  '385,455\n(+1,098)',
  '367,181',
  '381,190\n(+152)',
  '339,559\n(+1,926)',
  '347,693\n(+1,090)',
  '109,496\n(+557)',
  '350,430\n(+403)',
  '348,606\n(+259)',
  '308,938\n(+543)',
  '256,121',
  '299,479\n(+212)',
  '270,928\n(+1,796)',
  '297,252\n(+335)',
  '255,059\n(+588)',
  '284,712',
  '273,303\n(+1,385)',
  '273,920\n(+661)',
  '272,738\n(+61)',
  '240,730\n(+425)',
  '240,672',
  '234,545\n(+120)',
  '192,218',
  '204,847\n(+102)',
  '192,951\n(+331)',
  '138,961\n(+109)',
  '171,375',
  '88,952',
  '173,005\n(+93)',
  '173,004\n(+953)',
  '167,700\n(+501)',
  '154,694\n(+1,075)',
  '144,715',
  '124,362\n(+349)',
  '142,671\n(+186)',
  '146,588\n(+34)',
  '46,000',
  '121,363\n(+1,218)',
  '122,446\n(+197)',
  '122,753\n(+19)',
  '122,456\n(+578)',
  '96,059',
  '90,755',
  '101,690\n(+505)',
  '105,323',
  '86,851\n(+1,870)',
  '74,781',
  '45,465\n(+1)',
  '90,463\n(+61)',
  '75,176\n(+524)',
  '80,433',
  '82,676\n(+109)',
  '52,292\n(+195)',
  '76,026\n(+261)',
  '71,694\n(+82)',
  '54,668\n(+75)',
  '57,606\n(+127)',
  '30,858',
  '47,328\n(+55)',
  '52,010',
  '2,250',
  '36,724\n(+17)',
  '44,378\n(+202)',
  '43,983\n(+92)',
  '41,322',
  '104',
  '26,881\n(+17)',
  '33,500',
  '9,995',
  '32,044\n(+6)',
  '36,490\n(+42)',
  '35,896\n(+37)',
  '34,399\n(+108)',
  '23,599\n(+71)',
  '26,557\n(+287)',
  '28,752\n(+19)',
  '26,641\n(+100)',
  '22,433\n(+112)',
  '17,294',
  '5,568',
  '19,463\n(+115)',
  '20,903\n(+246)',
  '18,321\n(+56)',
  '2,964',
  '9,523\n(+109)',
  '17,568\n(+321)',
  '18,353',
  '18,493\n(+128)',
  '773',
  '16,960',
  '15,797\n(+31)',
  '13,742',
  '15,013\n(+18)',
  '1,854',
  '14,981\n(+15)',
  '14,271\n(+7)',
  '6,830',
  '12,421',
  '13,856\n(+44)',
  '4,225',
  '11,838',
  '11,897\n(+5)',
  '11,570\n(+148)',
  '10,225',
  '11,372\n(+121)',
  '6,859',
  '8,874\n(+72)',
  '9,571',
  '5,570',
  '6,634\n(+162)',
  '7,096\n(+31)',
  '58',
  '4,582\n(+139)',
  '6,628',
  '4,380',
  '5,283',
  '5,746\n(+11)',
  '5,458',
  '5,373\n(+8)',
  '5,310',
  '3,613\n(+295)',
  '4,853\n(+3)',
  '3,080\n(+221)',
  '4,012\n(+28)',
  '3,961\n(+16)',
  '3,960',
  '1,399',
  '3,355',
  '2,388\n(+7)',
  '2,680\n(+5)',
  '3,245\n(+3)',
  '2,680',
  '1,882',
  '2,749\n(+1)',
  '2,555',
  '2,593',
  '1,918',
  '976\n(+6)',
  '462',
  '183',
  '1,059\n(+8)',
  '761\n(+14)',
  '398',
  '438',
  '362\n(+17)',
  '63',
  '63',
  '30',
  '31',
  '27',
  '20',
  '8',
  '7',
  '5',
  '4',
  '3',
  '3',
  '2',
  '1'],
 ['1.6',
  '1.3',
  '2.8',
  '1.8',
  '2.8',
  '0.9',
  '1.7',
  '2.2',
  '2.2',
  '2.5',
  '1.7',
  '2.8',
  '2.2',
  '3.4',
  '7.6',
  '2.6',
  '3.0',
  '1.5',
  '2.3',
  '1.2',
  '9.2',
  '0.9',
  '1.1',
  '1.0',
  '1.8',
  '2.3',
  '1.7',
  '1.0',
  '1.8',
  '0.6',
  '2.2',
  '2.1',
  '3.0',
  '1.3',
  '1.7',
  '1.5',
  '0.9',
  '1.3',
  '0.8',
  '1.3',
  '3.7',
  '1.3',
  '1.4',
  '2.5',
  '1.5',
  '0.3',
  '3.5',
  '2.3',
  '1.3',
  '1.5',
  '2.4',
  '1.6',
  '0.8',
  '1.2',
  '2.5',
  '6.4',
  '3.7',
  '4.2',
  '1.3',
  '1.5',
  '3.5',
  '3.8',
  '0.6',
  '3.1',
  '2.1',
  '1.0',
  '1.6',
  '1.4',
  '1.2',
  '2.7',
  '0.7',
  '1.1',
  '1.6',
  '1.4',
  '1.5',
  '0.8',
  '1.3',
  '5.7',
  '0.4',
  '1.6',
  '2.3',
  '0.5',
  '2.0',
  '2.1',
  '0.3',
  '4.5',
  '1.7',
  '1.3',
  '2.9',
  '3.5',
  '0.5',
  '1.5',
  '1.3',
  '0.7',
  '1.6',
  '1.7',
  '4.6',
  '0.9',
  '1.3',
  '0.8',
  '1.5',
  '3.5',
  '2.7',
  '0.9',
  '2.6',
  '0.5',
  '2.1',
  '2.1',
  '3.1',
  '1.2',
  '1.3',
  '4.8',
  '0.1',
  '1.6',
  '0.3',
  '2.2',
  '1.1',
  '2.5',
  '3.7',
  '1.0',
  '1.9',
  '2.7',
  '0.7',
  '1.3',
  '1.2',
  '2.9',
  '2.6',
  '2.2',
  '1.4',
  '2.1',
  '1.5',
  '0.6',
  '7.6',
  '0.9',
  '1.2',
  '2.2',
  '6.6',
  '2.5',
  '1.2',
  '0.6',
  '0.9',
  '0.7',
  '0.1',
  '2.8',
  '0.5',
  '2.5',
  '0.9',
  '5.6',
  '2.0',
  '1.2',
  '0.6',
  '0.2',
  '0.7',
  '1.0',
  '5.2',
  '1.1',
  '0.5',
  '0.9',
  '3.6',
  '2.8',
  '1.4',
  '1.3',
  '1.5',
  '1.3',
  '1.7',
  '1.1',
  '1.2',
  '0.3',
  '0.9',
  '1.7',
  '3.4',
  '18.9',
  '0.9',
  '0.7',
  '1.5',
  '0.6',
  '0.6',
  '1.9',
  '2.2',
  '3.4',
  '4.9',
  '1.8',
  '1.7',
  '1.2',
  '3.5',
  '2.6',
  '1.6',
  '0.6',
  '3.6',
  '1.5',
  '1.7',
  '0.5',
  '1.5',
  '1.0',
  '0.5',
  '2.2',
  '0.8',
  '1.4',
  '0.1',
  '0.9',
  '0.6',
  '0.2',
  '3.7',
  '0.2',
  '0.2',
  '-',
  '1.6',
  '0.3',
  '-',
  '-',
  '3.0',
  '-',
  '-',
  '-',
  '10',
  '22.2',
  '-',
  '-',
  '25',
  '-',
  '-',
  '-'],
 ['76.0',
  '97.8',
  '95.3',
  '80.7',
  '88.9',
  '92.3',
  '96.3',
  '89.7',
  '97.4',
  '96.8',
  '95.6',
  '95.0',
  '94.4',
  '95.7',
  '82.3',
  '91.7',
  '95.4',
  '93.3',
  '93.6',
  '90.8',
  'N/A',
  'N/A',
  '95.3',
  '96.8',
  '97.8',
  '97.3',
  '95.4',
  '91.6',
  '97.4',
  '94.9',
  '93.8',
  '93.1',
  '91.2',
  'N/A',
  '95.5',
  '96.9',
  '85.5',
  '92.6',
  '95.4',
  '90.7',
  '95.4',
  '97.2',
  '96.3',
  '72.7',
  '95.8',
  '99.0',
  '95.5',
  '93.8',
  '94.9',
  '95.3',
  '92.3',
  '98.0',
  '96.6',
  '80.8',
  '88.5',
  '87.3',
  '91.8',
  '87.3',
  '94.1',
  '97.7',
  '96.3',
  '90.1',
  '99.2',
  '94.4',
  '96.1',
  '92.0',
  '98.1',
  '88.0',
  '95.3',
  '30.0',
  '97.9',
  '97.5',
  '90.3',
  '75.8',
  '91.3',
  '88.6',
  '97.9',
  '84.4',
  '95.2',
  '93.9',
  '94.4',
  '99.2',
  '92.7',
  '96.8',
  '99.2',
  '82.5',
  '98.1',
  '94.2',
  '68.5',
  '90.2',
  '47.3',
  '97.0',
  '97.2',
  '97.0',
  '92.0',
  '92.8',
  '80.2',
  '92.2',
  '97.4',
  '32.8',
  '93.0',
  '94.2',
  '96.4',
  '96.4',
  '77.9',
  '76.8',
  '91.8',
  '98.0',
  '83.2',
  '74.1',
  '46.9',
  '94.2',
  '84.0',
  '94.2',
  '97.9',
  '63.0',
  '97.6',
  '97.2',
  '88.9',
  '96.0',
  '54.3',
  '85.1',
  '97.7',
  '4.2',
  '72.2',
  '88.7',
  '96.0',
  '96.3',
  '0.3',
  '66.4',
  '83.4',
  '25.1',
  '83.8',
  '97.4',
  '96.7',
  '95.8',
  '70.8',
  '85.0',
  '94.7',
  '90.3',
  '88.8',
  '75.3',
  '24.8',
  '89.9',
  '97.9',
  '88.2',
  '14.6',
  '47.7',
  '88.1',
  '94.0',
  '95.1',
  '4.4',
  '99.3',
  '96.4',
  '84.8',
  '97.3',
  '12.0',
  '98.6',
  '94.1',
  '47.4',
  '87.2',
  '97.6',
  '30.8',
  '96.6',
  '97.4',
  '96.8',
  '86.6',
  '96.7',
  '60.3',
  '79.0',
  '96.4',
  '62.0',
  '85.4',
  '95.2',
  '0.8',
  '67.3',
  '99.0',
  '68.5',
  '86.6',
  '95.9',
  '94.2',
  '97.1',

In [19]:
for i in range(9):
    print(len(all_data[i]))

222
222
222
222
222
222
222
222
222

In [20]:
import pandas as pd

dict_dat = { "국가":all_data[0], 
             "확진자":all_data[1],
             "위중증":all_data[2],
             "사망자":all_data[3],
             "완치":all_data[4],
             "치명(%)":all_data[5],
             "완치(%)":all_data[6],
             "발생률":all_data[7],
             "인구수":all_data[8]
           }

dat = pd.DataFrame(dict_dat)
dat

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수
0,미국🇺🇸,"43,942,335\n(+187,382)","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651"
1,인도🇮🇳,"33,714,241\n(+21,093)","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385"
2,브라질🇧🇷,"21,366,395\n(+14,423)","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417"
3,영국🇬🇧,"7,701,715\n(+37,485)",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011"
4,러시아🇷🇺,"7,464,708\n(+21,559)","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462"
...,...,...,...,...,...,...,...,...,...
217,마셜 제도🇲🇭,4,N/A,0,4,-,100,68,"59,190"
218,바누아투🇻🇺,4,N/A,1,3,25,75,13,"307,145"
219,사모아🇼🇸,3,N/A,0,3,-,100,15,"198,414"
220,세인트헬레나🇸🇭,2,N/A,0,2,-,100,329,"6,077"
221,미크로네시아🇫🇲,1,N/A,0,1,-,100,9,"115,023"

#### 2-7 (실습) 확진자 정보를 (전체, 증감)

In [21]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국가      222 non-null    object
 1   확진자     222 non-null    object
 2   위중증     222 non-null    object
 3   사망자     222 non-null    object
 4   완치      222 non-null    object
 5   치명(%)   222 non-null    object
 6   완치(%)   222 non-null    object
 7   발생률     222 non-null    object
 8   인구수     222 non-null    object
dtypes: object(9)
memory usage: 15.7+ KB

In [22]:
dat['확진자'].head()

0    43,942,335\n(+187,382)
1     33,714,241\n(+21,093)
2     21,366,395\n(+14,423)
3      7,701,715\n(+37,485)
4      7,464,708\n(+21,559)
Name: 확진자, dtype: object

In [23]:
dat[['확진자', '확진자_증감']] = dat['확진자'].str.split('\n', n=2, expand=True)
dat.head()

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수,확진자_증감
0,미국🇺🇸,"43,942,335","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651","(+187,382)"
1,인도🇮🇳,"33,714,241","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385","(+21,093)"
2,브라질🇧🇷,"21,366,395","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417","(+14,423)"
3,영국🇬🇧,"7,701,715",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011","(+37,485)"
4,러시아🇷🇺,"7,464,708","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462","(+21,559)"

#### 2-8 (실습) 사망자 정보를  (사망자, 증감)

In [24]:
dat['사망자'].head()

0    709,119\n(+2,781)
1      447,699\n(+337)
2      594,702\n(+218)
3       136,208\n(+40)
4      205,531\n(+852)
Name: 사망자, dtype: object

In [25]:
dat[['사망자', '사망자_증감']] = dat['사망자'].str.split('\n', n=2, expand=True)
dat.head()

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수,확진자_증감,사망자_증감
0,미국🇺🇸,"43,942,335","21,819\n(-275)","709,119","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651","(+187,382)","(+2,781)"
1,인도🇮🇳,"33,714,241","8,944","447,699","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385","(+21,093)",(+337)
2,브라질🇧🇷,"21,366,395","8,318","594,702","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417","(+14,423)",(+218)
3,영국🇬🇧,"7,701,715",878\n(-38),"136,208","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011","(+37,485)",(+40)
4,러시아🇷🇺,"7,464,708","2,300","205,531","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462","(+21,559)",(+852)

## 데이터 전처리

In [26]:
import pandas as pd

dict_dat = { "국가":all_data[0], 
             "확진자":all_data[1],
             "위중증":all_data[2],
             "사망자":all_data[3],
             "완치":all_data[4],
             "치명(%)":all_data[5],
             "완치(%)":all_data[6],
             "발생률":all_data[7],
             "인구수":all_data[8]
           }

dat = pd.DataFrame(dict_dat)
dat

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수
0,미국🇺🇸,"43,942,335\n(+187,382)","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651"
1,인도🇮🇳,"33,714,241\n(+21,093)","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385"
2,브라질🇧🇷,"21,366,395\n(+14,423)","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417"
3,영국🇬🇧,"7,701,715\n(+37,485)",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011"
4,러시아🇷🇺,"7,464,708\n(+21,559)","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462"
...,...,...,...,...,...,...,...,...,...
217,마셜 제도🇲🇭,4,N/A,0,4,-,100,68,"59,190"
218,바누아투🇻🇺,4,N/A,1,3,25,75,13,"307,145"
219,사모아🇼🇸,3,N/A,0,3,-,100,15,"198,414"
220,세인트헬레나🇸🇭,2,N/A,0,2,-,100,329,"6,077"
221,미크로네시아🇫🇲,1,N/A,0,1,-,100,9,"115,023"

In [27]:
dat['확진자']

0      43,942,335\n(+187,382)
1       33,714,241\n(+21,093)
2       21,366,395\n(+14,423)
3        7,701,715\n(+37,485)
4        7,464,708\n(+21,559)
                ...
217                         4
218                         4
219                         3
220                         2
221                         1
Name: 확진자, Length: 222, dtype: object

In [28]:
dat['확진자'].str.split('\n')

0      [43,942,335, (+187,382)]
1       [33,714,241, (+21,093)]
2       [21,366,395, (+14,423)]
3        [7,701,715, (+37,485)]
4        [7,464,708, (+21,559)]
                 ...
217                         [4]
218                         [4]
219                         [3]
220                         [2]
221                         [1]
Name: 확진자, Length: 222, dtype: object

In [29]:
dat['확진자'].str.split('\n')[0]

['43,942,335', '(+187,382)']

In [30]:
dat['확진자'].str.split('\n').str[0]

0      43,942,335
1      33,714,241
2      21,366,395
3       7,701,715
4       7,464,708
          ...
217             4
218             4
219             3
220             2
221             1
Name: 확진자, Length: 222, dtype: object

### 확진자를 확진자_합계와 확진자1일로 나누기

In [31]:
dat['확진자_합계'] = dat['확진자'].str.split('\n').str[0]
dat['확진자1일'] = dat['확진자'].str.split('\n').str[1]

In [32]:
dat.head()

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일
0,미국🇺🇸,"43,942,335\n(+187,382)","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651","43,942,335","(+187,382)"
1,인도🇮🇳,"33,714,241\n(+21,093)","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385","33,714,241","(+21,093)"
2,브라질🇧🇷,"21,366,395\n(+14,423)","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417","21,366,395","(+14,423)"
3,영국🇬🇧,"7,701,715\n(+37,485)",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011","7,701,715","(+37,485)"
4,러시아🇷🇺,"7,464,708\n(+21,559)","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462","7,464,708","(+21,559)"

### 사망자를 사망자합계와 사망자1일로 나누기

In [33]:
dat['사망자합계'] = dat['사망자'].str.split('\n').str[0]
dat['사망자1일'] = dat['사망자'].str.split('\n').str[1]

In [34]:
dat.head()

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일
0,미국🇺🇸,"43,942,335\n(+187,382)","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651","43,942,335","(+187,382)","709,119","(+2,781)"
1,인도🇮🇳,"33,714,241\n(+21,093)","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385","33,714,241","(+21,093)","447,699",(+337)
2,브라질🇧🇷,"21,366,395\n(+14,423)","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417","21,366,395","(+14,423)","594,702",(+218)
3,영국🇬🇧,"7,701,715\n(+37,485)",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011","7,701,715","(+37,485)","136,208",(+40)
4,러시아🇷🇺,"7,464,708\n(+21,559)","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462","7,464,708","(+21,559)","205,531",(+852)

### 완치를 완치합계와 완치1일로 나누기

In [35]:
dat['완치합계'] = dat['완치'].str.split('\n').str[0]
dat['완치1일'] = dat['완치'].str.split('\n').str[1]

In [36]:
dat.head()

,국가,확진자,위중증,사망자,완치,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일,완치합계,완치1일
0,미국🇺🇸,"43,942,335\n(+187,382)","21,819\n(-275)","709,119\n(+2,781)","33,394,833\n(+208,564)",1.6,76.0,"133,095","331,002,651","43,942,335","(+187,382)","709,119","(+2,781)","33,394,833","(+208,564)"
1,인도🇮🇳,"33,714,241\n(+21,093)","8,944","447,699\n(+337)","32,976,760\n(+28,144)",1.3,97.8,"24,431","1,380,004,385","33,714,241","(+21,093)","447,699",(+337),"32,976,760","(+28,144)"
2,브라질🇧🇷,"21,366,395\n(+14,423)","8,318","594,702\n(+218)","20,361,191\n(+20,818)",2.8,95.3,"100,592","212,559,417","21,366,395","(+14,423)","594,702",(+218),"20,361,191","(+20,818)"
3,영국🇬🇧,"7,701,715\n(+37,485)",878\n(-38),"136,208\n(+40)","6,219,111\n(+33,541)",1.8,80.7,"113,959","67,886,011","7,701,715","(+37,485)","136,208",(+40),"6,219,111","(+33,541)"
4,러시아🇷🇺,"7,464,708\n(+21,559)","2,300","205,531\n(+852)","6,635,485\n(+17,368)",2.8,88.9,"51,151","145,934,462","7,464,708","(+21,559)","205,531",(+852),"6,635,485","(+17,368)"

### '확진자, 사망자, 완치' 열을 없애기

In [37]:
dat = dat.drop( [ '확진자', '사망자', '완치'], axis=1)
dat.head()

,국가,위중증,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일,완치합계,완치1일
0,미국🇺🇸,"21,819\n(-275)",1.6,76.0,"133,095","331,002,651","43,942,335","(+187,382)","709,119","(+2,781)","33,394,833","(+208,564)"
1,인도🇮🇳,"8,944",1.3,97.8,"24,431","1,380,004,385","33,714,241","(+21,093)","447,699",(+337),"32,976,760","(+28,144)"
2,브라질🇧🇷,"8,318",2.8,95.3,"100,592","212,559,417","21,366,395","(+14,423)","594,702",(+218),"20,361,191","(+20,818)"
3,영국🇬🇧,878\n(-38),1.8,80.7,"113,959","67,886,011","7,701,715","(+37,485)","136,208",(+40),"6,219,111","(+33,541)"
4,러시아🇷🇺,"2,300",2.8,88.9,"51,151","145,934,462","7,464,708","(+21,559)","205,531",(+852),"6,635,485","(+17,368)"

### 각 열에 있는 괄호, 쉼표 제거(정규표현식 이용)

In [38]:
# 위중증 쉼표, 괄호 제거
dat['위중증'] = dat['위중증'].str.replace(pat=r'[,()]', repl=r'', regex=True)
# 발생률 쉼표 제거
dat['발생률'] = dat['발생률'].str.replace(pat=r'[,]', repl=r'', regex=True)
# 인구수 쉼표 제거
dat['인구수'] = dat['인구수'].str.replace(pat=r'[,]', repl=r'', regex=True)
# 확진자 합계 쉼표 제거
dat['확진자_합계'] = dat['확진자_합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
# 확진자1일 쉼표, 괄호 제거
dat['확진자1일'] = dat['확진자1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)
# 사망자합계 쉼표 제거
dat['사망자합계'] = dat['사망자합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
# 사망자1일 쉼표, 괄호 제거
dat['사망자1일'] = dat['사망자1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)
# 완치합계 쉼표 제거
dat['완치합계'] = dat['완치합계'].str.replace(pat=r'[,]', repl=r'', regex=True)
# 완치1일 쉼표, 괄호 제거
dat['완치1일'] = dat['완치1일'].str.replace(pat=r'[,()]', repl=r'', regex=True)

In [39]:
dat.head()

,국가,위중증,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일,완치합계,완치1일
0,미국🇺🇸,21819\n-275,1.6,76.0,133095,331002651,43942335,+187382,709119,+2781,33394833,+208564
1,인도🇮🇳,8944,1.3,97.8,24431,1380004385,33714241,+21093,447699,+337,32976760,+28144
2,브라질🇧🇷,8318,2.8,95.3,100592,212559417,21366395,+14423,594702,+218,20361191,+20818
3,영국🇬🇧,878\n-38,1.8,80.7,113959,67886011,7701715,+37485,136208,+40,6219111,+33541
4,러시아🇷🇺,2300,2.8,88.9,51151,145934462,7464708,+21559,205531,+852,6635485,+17368

### 위중증을 위중증합계와 위중증1일로 나누기

In [40]:
dat['위중증합계'] = dat['위중증'].str.split('\n').str[0]
dat['위중증1일'] = dat['위중증'].str.split('\n').str[1]
dat.head()

,국가,위중증,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일,완치합계,완치1일,위중증합계,위중증1일
0,미국🇺🇸,21819\n-275,1.6,76.0,133095,331002651,43942335,+187382,709119,+2781,33394833,+208564,21819,-275
1,인도🇮🇳,8944,1.3,97.8,24431,1380004385,33714241,+21093,447699,+337,32976760,+28144,8944,NaN
2,브라질🇧🇷,8318,2.8,95.3,100592,212559417,21366395,+14423,594702,+218,20361191,+20818,8318,NaN
3,영국🇬🇧,878\n-38,1.8,80.7,113959,67886011,7701715,+37485,136208,+40,6219111,+33541,878,-38
4,러시아🇷🇺,2300,2.8,88.9,51151,145934462,7464708,+21559,205531,+852,6635485,+17368,2300,NaN

### 위중증 열 제거하기

In [41]:
dat = dat.drop(['위중증'], axis=1)
dat.head()

,국가,치명(%),완치(%),발생률,인구수,확진자_합계,확진자1일,사망자합계,사망자1일,완치합계,완치1일,위중증합계,위중증1일
0,미국🇺🇸,1.6,76.0,133095,331002651,43942335,+187382,709119,+2781,33394833,+208564,21819,-275
1,인도🇮🇳,1.3,97.8,24431,1380004385,33714241,+21093,447699,+337,32976760,+28144,8944,NaN
2,브라질🇧🇷,2.8,95.3,100592,212559417,21366395,+14423,594702,+218,20361191,+20818,8318,NaN
3,영국🇬🇧,1.8,80.7,113959,67886011,7701715,+37485,136208,+40,6219111,+33541,878,-38
4,러시아🇷🇺,2.8,88.9,51151,145934462,7464708,+21559,205531,+852,6635485,+17368,2300,NaN

In [42]:
from datetime import datetime
from datetime import date
import datetime
import os

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)

# print(today)
# print(yesterday)
if flag_today == True:
    file_make_time = today
else:
    file_make_time = yesterday

print( file_make_time )

print( os.getcwd() )
path_dir = os.getcwd() + "\\data\\"
path_file = path_dir + str(file_make_time)
print( path_dir,  path_file, sep="\n" )

2021-09-28
D:\Data\documents\GitHub\LikeLion_13th_DataCourse\codeclass\2021.09.29
D:\Data\documents\GitHub\LikeLion_13th_DataCourse\codeclass\2021.09.29\data\
D:\Data\documents\GitHub\LikeLion_13th_DataCourse\codeclass\2021.09.29\data\2021-09-28

In [43]:
dat.to_csv(path_file + "_corona.csv", index=False)
dat.to_excel(path_file + "_corona.xlsx", index=False)
os.listdir( path_dir )

['2021-09-28_corona.csv', '2021-09-28_corona.xlsx']